#include "orchard.hpp"

#include <fstream>
#include <gtest/gtest.h>

using namespace bb;
using namespace bb::zcash;

/**
 * Generates orchard_fixed_base_z_bn254.hpp: the z-values of the Grumpkin fixed bases of Orchard<Bn254Cycle> (the
 * smallest z per window, as find_zs computes them). Run manually; the output path is the first command-line-free
 * environment variable ZCASH_Z_OUT.
 */
TEST(ZcashFixedBaseZ, DISABLED_GenerateBn254)
{
    using O = Orchard<Bn254Cycle>;
    const auto& k = O::constants();
    const char* out_path = std::getenv("ZCASH_Z_OUT");
    ASSERT_NE(out_path, nullptr);
    std::ofstream out(out_path);
    out << "#pragma once\n\n#include <array>\n#include <cstdint>\n\n"
           "// Generated by fixed_base_z_gen.test.cpp (ZcashFixedBaseZ.DISABLED_GenerateBn254): z-values of the\n"
           "// Orchard<Bn254Cycle> fixed bases, the smallest z per window with y + z square and -y + z non-square for\n"
           "// all eight window points.\n"
           "namespace bb::zcash::orchard_constants_bn254 {\n\n";
    auto emit = [&](const char* name, const Bn254Cycle::AffineElement& g, size_t windows) {
        const auto zs = FixedBase<Bn254Cycle>::find_zs(g, windows);
        out << "inline constexpr std::array<uint64_t, " << windows << "> " << name << " = {";
        for (size_t i = 0; i < zs.size(); ++i) {
            out << (i % 8 == 0 ? "\n    " : " ") << zs[i] << "ULL,";
        }
        out << "\n};\n\n";
        out.flush();
    };
    emit("SPEND_AUTH_G_Z", k.spend_auth_g, O::NUM_WINDOWS);
    emit("VALUE_COMMIT_R_Z", k.value_commit_r, O::NUM_WINDOWS);
    emit("NOTE_COMMIT_R_Z", k.note_commit_r, O::NUM_WINDOWS);
    emit("COMMIT_IVK_R_Z", k.commit_ivk_r, O::NUM_WINDOWS);
    emit("NULLIFIER_K_Z", k.nullifier_k, O::NUM_WINDOWS);
    emit("VALUE_COMMIT_V_Z", k.value_commit_v, O::NUM_WINDOWS_SHORT);
    out << "} // namespace bb::zcash::orchard_constants_bn254\n";
}
