#pragma once

#include "barretenberg/ecc/curves/bn254/fr.hpp"
#include "barretenberg/numeric/uint256/uint256.hpp"

#include <cstddef>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace bb::pcs_recursion {

/**
 * @brief Emitter for the two files a Noir recursive-verifier package consumes.
 *
 * @details `params.nr` carries every structural constant of one proof family - array lengths, per
 * round query counts, tree depths, claim layout - because Noir array sizes and loop bounds must be
 * known at compile time. `Prover.toml` carries the one proof's field elements. A verifier compiled
 * against a given `params.nr` therefore verifies any proof of that family; regenerating it is what a
 * parameter sweep does.
 */
class NoirWriter {
  public:
    explicit NoirWriter(std::string path)
        : path_(std::move(path))
    {}

    void comment(const std::string& text) { body_ << "// " << text << "\n"; }
    void blank() { body_ << "\n"; }

    void global_u32(const std::string& name, size_t value)
    {
        body_ << "pub global " << name << ": u32 = " << value << ";\n";
    }

    void global_field(const std::string& name, const fr& value)
    {
        body_ << "pub global " << name << ": Field = " << to_hex(value) << ";\n";
    }

    void global_bool(const std::string& name, bool value)
    {
        body_ << "pub global " << name << ": bool = " << (value ? "true" : "false") << ";\n";
    }

    void global_u32_array(const std::string& name, const std::vector<size_t>& values)
    {
        body_ << "pub global " << name << ": [u32; " << std::max(values.size(), size_t(1)) << "] = [";
        if (values.empty()) {
            body_ << "0"; // Noir has no zero-length array literal; unused when the count global is 0
        }
        for (size_t i = 0; i < values.size(); ++i) {
            body_ << (i == 0 ? "" : ", ") << values[i];
        }
        body_ << "];\n";
    }

    void global_field_array(const std::string& name, const std::vector<fr>& values)
    {
        body_ << "pub global " << name << ": [Field; " << std::max(values.size(), size_t(1)) << "] = [";
        if (values.empty()) {
            body_ << "0";
        }
        for (size_t i = 0; i < values.size(); ++i) {
            body_ << (i == 0 ? "" : ", ") << to_hex(values[i]);
        }
        body_ << "];\n";
    }

    void global_bool_array(const std::string& name, const std::vector<bool>& values)
    {
        body_ << "pub global " << name << ": [bool; " << std::max(values.size(), size_t(1)) << "] = [";
        if (values.empty()) {
            body_ << "false";
        }
        for (size_t i = 0; i < values.size(); ++i) {
            body_ << (i == 0 ? "" : ", ") << (values[i] ? "true" : "false");
        }
        body_ << "];\n";
    }

    void write() const
    {
        std::ofstream out(path_);
        out << "// Generated by pcs_noir_export. Do not edit.\n";
        out << body_.str();
    }

    static std::string to_hex(const fr& value)
    {
        std::ostringstream stream;
        stream << "0x" << std::hex;
        const uint256_t canonical(value);
        bool started = false;
        for (size_t limb = 4; limb-- > 0;) {
            for (size_t nibble = 16; nibble-- > 0;) {
                const uint64_t digit = (canonical.data[limb] >> (4 * nibble)) & 0xf;
                if (digit != 0 || started || (limb == 0 && nibble == 0)) {
                    started = true;
                    stream << digit;
                }
            }
        }
        return stream.str();
    }

  private:
    std::string path_;
    std::ostringstream body_;
};

/** @brief Emitter for `Prover.toml`: named flat arrays of field elements and small integers. */
class TomlWriter {
  public:
    explicit TomlWriter(std::string path)
        : path_(std::move(path))
    {}

    void field(const std::string& name, const fr& value) { body_ << name << " = \"" << decimal(value) << "\"\n"; }

    void field_array(const std::string& name, const std::vector<fr>& values)
    {
        body_ << name << " = [";
        for (size_t i = 0; i < values.size(); ++i) {
            body_ << (i == 0 ? "" : ", ") << "\"" << decimal(values[i]) << "\"";
        }
        body_ << "]\n";
    }

    /** @brief `name = [[...], [...]]`: a flat vector reshaped into rows of `width`. */
    void field_array_2d(const std::string& name, const std::vector<fr>& values, size_t width)
    {
        body_ << name << " = [";
        for (size_t row = 0; row * width < values.size(); ++row) {
            body_ << (row == 0 ? "" : ", ") << "[";
            for (size_t i = 0; i < width; ++i) {
                body_ << (i == 0 ? "" : ", ") << "\"" << decimal(values[row * width + i]) << "\"";
            }
            body_ << "]";
        }
        body_ << "]\n";
    }

    void u32_array(const std::string& name, const std::vector<size_t>& values)
    {
        body_ << name << " = [";
        for (size_t i = 0; i < values.size(); ++i) {
            body_ << (i == 0 ? "" : ", ") << "\"" << values[i] << "\"";
        }
        body_ << "]\n";
    }

    void write() const
    {
        std::ofstream out(path_);
        out << body_.str();
    }

    static std::string decimal(const fr& value)
    {
        const uint256_t canonical(value);
        if (canonical == uint256_t(0)) {
            return "0";
        }
        std::string digits;
        uint256_t remaining = canonical;
        while (remaining > uint256_t(0)) {
            const uint256_t quotient = remaining / uint256_t(10);
            const uint64_t digit = static_cast<uint64_t>((remaining - quotient * uint256_t(10)).data[0]);
            digits.push_back(static_cast<char>('0' + digit));
            remaining = quotient;
        }
        return std::string(digits.rbegin(), digits.rend());
    }

  private:
    std::string path_;
    std::ostringstream body_;
};

} // namespace bb::pcs_recursion
