#include "barretenberg/srs/global_crs.hpp"
#include "barretenberg/stdlib/hash/poseidon2/poseidon2.hpp"
#include "barretenberg/stdlib/primitives/bigfield/bigfield.hpp"
#include "barretenberg/stdlib_circuit_builders/plookup_tables/fixed_base/fixed_base.hpp"
#include "barretenberg/ultra_fflonk/prover.hpp"
#include "barretenberg/ultra_fflonk/relation_batch.hpp"
#include "barretenberg/ultra_fflonk/verifier.hpp"

#include <chrono>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

using namespace bb;
using namespace bb::ultra_fflonk;

namespace {

using Builder = Flavor::CircuitBuilder;

std::string hex(const uint256_t& value)
{
    static constexpr std::string_view DIGITS = "0123456789abcdef";
    std::string out = "0x";
    for (size_t limb = 4; limb-- > 0;) {
        for (size_t nibble = 16; nibble-- > 0;) {
            out += DIGITS[(value.data[limb] >> (4 * nibble)) & 0xf];
        }
    }
    return out;
}

std::string hex(const FF& value)
{
    return hex(static_cast<uint256_t>(value));
}

std::string hex_bytes(std::span<const uint8_t> bytes)
{
    static constexpr std::string_view DIGITS = "0123456789abcdef";
    std::string out = "hex\"";
    for (const uint8_t byte : bytes) {
        out += DIGITS[byte >> 4];
        out += DIGITS[byte & 0xf];
    }
    out += "\"";
    return out;
}

/**
 * @brief Random rows and the value of every subrelation on them, as barretenberg computes it.
 *
 * @details The Solidity relation set is a hand port of nine C++ templates, and `alpha` folds all
 * thirty-one subrelations into one number - inside which a single wrong term is invisible. Exporting
 * the values *unbatched* is what lets the Foundry test say which relation a port got wrong, rather
 * than only that a proof failed.
 *
 * The rows are uniformly random, which is the right choice here: this is a differential test between
 * two evaluations of the same polynomial, not a satisfiability test, so random inputs exercise every
 * term and no term can be accidentally masked by a zero selector.
 */
std::string emit_relation_vectors(const size_t count)
{
    std::string out;
    out += "// SPDX-License-Identifier: Apache-2.0\n";
    out += "// AUTOGENERATED by ultra_fflonk_solidity_export_bench. Do not edit.\n";
    out += "pragma solidity >=0.8.21;\n\n";
    out += "/// @dev Random rows and barretenberg's own value for each of the 31 subrelations on them.\n";
    out += "library RelationVectors {\n";
    out += "    uint256 internal constant COUNT = " + std::to_string(count) + ";\n";
    out += "    uint256 internal constant NUM_ENTITIES = 41;\n";
    out += "    uint256 internal constant NUM_SUBRELATIONS = 31;\n\n";
    out += "    struct Case {\n";
    out += "        uint256[41] e;\n";
    out +=
        "        uint256[9] params; // eta, etaTwo, etaThree, romLogupGamma, beta, gamma, delta, betaSqr, betaCube\n";
    out += "        uint256[31] expected;\n";
    out += "    }\n\n";
    out += "    function get(uint256 index) internal pure returns (Case memory c) {\n";

    for (size_t i = 0; i < count; ++i) {
        Flavor::AllValues row;
        for (FF& value : row.data) {
            value = FF::random_element();
        }

        RelationParameters<FF> parameters;
        parameters.compute_eta_powers(FF::random_element());
        parameters.rom_logup_gamma = FF::random_element();
        parameters.compute_beta_powers(FF::random_element());
        parameters.gamma = FF::random_element();
        parameters.public_input_delta = FF::random_element();

        const std::array<FF, NUM_SUBRELATIONS> expected = all_subrelations(row, parameters);

        out += "        if (index == " + std::to_string(i) + ") {\n";
        for (size_t k = 0; k < row.data.size(); ++k) {
            out += "            c.e[" + std::to_string(k) + "] = " + hex(row.data[k]) + ";\n";
        }
        const std::array<FF, 9> flat_params = {
            parameters.eta,      parameters.eta_two, parameters.eta_three,          parameters.rom_logup_gamma,
            parameters.beta,     parameters.gamma,   parameters.public_input_delta, parameters.beta_sqr,
            parameters.beta_cube
        };
        for (size_t k = 0; k < flat_params.size(); ++k) {
            out += "            c.params[" + std::to_string(k) + "] = " + hex(flat_params[k]) + ";\n";
        }
        for (size_t k = 0; k < expected.size(); ++k) {
            out += "            c.expected[" + std::to_string(k) + "] = " + hex(expected[k]) + ";\n";
        }
        out += "            return c;\n        }\n";
    }

    out += "        revert(\"vector: no such case\");\n";
    out += "    }\n}\n";
    return out;
}

/** @brief A circuit of arithmetic gates only, padded towards `minimum_rows`. */
Builder arithmetic_circuit(const size_t num_public_inputs, const size_t num_gates)
{
    Builder builder;
    std::vector<uint32_t> publics;
    publics.reserve(num_public_inputs);
    for (size_t i = 0; i < num_public_inputs; ++i) {
        publics.push_back(builder.add_public_variable(FF(static_cast<uint64_t>(i) + 3)));
    }

    const uint32_t a_idx = publics.empty() ? builder.add_variable(FF(7)) : publics[0];
    const FF a = builder.get_variable(a_idx);
    const FF b = FF::random_element();
    const uint32_t b_idx = builder.add_variable(b);
    const uint32_t c_idx = builder.add_variable(a + b);
    for (size_t i = 0; i < num_gates; ++i) {
        builder.create_add_gate({ a_idx, b_idx, c_idx, 1, 1, -1, 0 });
    }
    return builder;
}

/**
 * @brief A circuit that lights up every gate selector, so the fixture's gas figure is the cost of a
 * verifier that really has to evaluate the whole relation set - lookups included.
 */
Builder assorted_circuit()
{
    Builder builder;

    const FF a = FF::random_element();
    const uint32_t a_idx = builder.add_public_variable(a);
    const FF b = FF::random_element();
    const FF c = a + b;
    const FF d = a + c;
    const uint32_t b_idx = builder.add_variable(b);
    const uint32_t c_idx = builder.add_variable(c);
    const uint32_t d_idx = builder.add_variable(d);
    for (size_t i = 0; i < 8; ++i) {
        builder.create_add_gate({ a_idx, b_idx, c_idx, 1, 1, -1, 0 });
        builder.create_add_gate({ d_idx, c_idx, a_idx, 1, -1, -1, 0 });
    }
    const uint32_t e_idx = builder.add_variable(a + b + c + d);
    builder.create_big_add_gate({ a_idx, b_idx, c_idx, d_idx, -1, -1, -1, -1, 0 }, true);
    builder.create_big_add_gate({ builder.zero_idx(), builder.zero_idx(), builder.zero_idx(), e_idx, 0, 0, 0, 0, 0 },
                                false);

    const FF pedersen_input = FF::random_element();
    const auto input_hi =
        uint256_t(pedersen_input)
            .slice(plookup::fixed_base::table::BITS_PER_LO_SCALAR,
                   plookup::fixed_base::table::BITS_PER_LO_SCALAR + plookup::fixed_base::table::BITS_PER_HI_SCALAR);
    const auto input_lo = uint256_t(pedersen_input).slice(0, plookup::fixed_base::table::BITS_PER_LO_SCALAR);
    builder.create_gates_from_plookup_accumulators(
        plookup::MultiTableId::FIXED_BASE_LEFT_HI,
        plookup::get_lookup_accumulators(plookup::MultiTableId::FIXED_BASE_LEFT_HI, input_hi),
        builder.add_variable(FF(input_hi)));
    builder.create_gates_from_plookup_accumulators(
        plookup::MultiTableId::FIXED_BASE_LEFT_LO,
        plookup::get_lookup_accumulators(plookup::MultiTableId::FIXED_BASE_LEFT_LO, input_lo),
        builder.add_variable(FF(input_lo)));

    builder.enforce_small_deltas({ builder.add_variable(FF(0)),
                                   builder.add_variable(FF(1)),
                                   builder.add_variable(FF(2)),
                                   builder.add_variable(FF(3)) });

    const grumpkin::g1::affine_element p1 = grumpkin::g1::affine_element::random_element();
    const grumpkin::g1::affine_element p2 = grumpkin::g1::affine_element::random_element();
    const grumpkin::g1::affine_element p3(grumpkin::g1::element(p1) - grumpkin::g1::element(p2));
    builder.create_ecc_add_gate({ builder.add_variable(p1.x),
                                  builder.add_variable(p1.y),
                                  builder.add_variable(p2.x),
                                  builder.add_variable(p2.y),
                                  builder.add_variable(p3.x),
                                  builder.add_variable(p3.y),
                                  /*is_addition=*/false });

    std::array<uint32_t, 8> ram_values{};
    for (uint32_t& value : ram_values) {
        value = builder.add_variable(FF::random_element());
    }
    const size_t ram_id = builder.create_RAM_array(ram_values.size());
    for (size_t i = 0; i < ram_values.size(); ++i) {
        builder.init_RAM_element(ram_id, i, ram_values[i]);
    }
    const uint32_t read_a = builder.read_RAM_array(ram_id, builder.add_variable(FF(5)));
    const uint32_t read_b = builder.read_RAM_array(ram_id, builder.add_variable(FF(1)));
    builder.write_RAM_array(ram_id, builder.add_variable(FF(4)), builder.add_variable(FF(500)));
    const uint32_t read_c = builder.read_RAM_array(ram_id, builder.add_variable(FF(4)));
    const uint32_t ram_sum = builder.add_variable(builder.get_variable(read_a) + builder.get_variable(read_b) +
                                                  builder.get_variable(read_c));
    builder.create_big_add_gate({ read_a, read_b, read_c, ram_sum, 1, 1, 1, -1, 0 }, false);

    {
        using fq_ct = stdlib::bigfield<Builder, Bn254FqParams>;
        const fq_ct x = fq_ct::from_witness(&builder, fq::random_element());
        const fq_ct y = fq_ct::from_witness(&builder, fq::random_element());
        [[maybe_unused]] const fq_ct product = x * y;
    }
    {
        using field_ct = stdlib::field_t<Builder>;
        using witness_ct = stdlib::witness_t<Builder>;
        std::vector<field_ct> inputs;
        inputs.reserve(4);
        for (size_t i = 0; i < 4; ++i) {
            inputs.emplace_back(witness_ct(&builder, FF::random_element()));
        }
        stdlib::poseidon2<Builder>::hash(inputs);
    }

    return builder;
}

struct ExportedCase {
    std::string label;
    ProvingKey key;
    Proof proof;
};

std::string emit_fixture(std::span<const ExportedCase> cases)
{
    std::string out;
    out += "// SPDX-License-Identifier: Apache-2.0\n";
    out += "// AUTOGENERATED by ultra_fflonk_solidity_export_bench. Do not edit.\n";
    out += "//\n";
    out += "// Every proof here was verified by barretenberg's own verifier before it was written out,\n";
    out += "// so a passing acceptance test is two independent implementations agreeing on one proof.\n";
    out += "pragma solidity >=0.8.21;\n\n";
    out += "library Fixture {\n";
    out += "    uint256 internal constant COUNT = " + std::to_string(cases.size()) + ";\n\n";
    out += "    struct Case {\n";
    out += "        string label;\n";
    out += "        uint256 circuitSize;\n";
    out += "        uint256 numPublicInputs;\n";
    out += "        uint256 pubInputsOffset;\n";
    out += "        uint256 omega;\n";
    out += "        uint256[8] preprocessed;\n";
    out += "        bytes proof;\n";
    out += "        uint256[] publicInputs;\n";
    out += "    }\n\n";
    out += "    function get(uint256 index) internal pure returns (Case memory c) {\n";

    for (size_t i = 0; i < cases.size(); ++i) {
        const ExportedCase& exported = cases[i];
        const VerificationKey& vk = exported.key.verification_key;
        out += "        if (index == " + std::to_string(i) + ") {\n";
        out += "            c.label = \"" + exported.label + "\";\n";
        out += "            c.circuitSize = " + std::to_string(vk.circuit_size) + ";\n";
        out += "            c.numPublicInputs = " + std::to_string(vk.num_public_inputs) + ";\n";
        out += "            c.pubInputsOffset = " + std::to_string(vk.pub_inputs_offset) + ";\n";
        out += "            c.omega = " + hex(vk.omega) + ";\n";
        for (size_t g = 0; g < NUM_PREPROCESSED_GROUPS; ++g) {
            out += "            c.preprocessed[" + std::to_string(2 * g) +
                   "] = " + hex(static_cast<uint256_t>(vk.preprocessed[g].x)) + ";\n";
            out += "            c.preprocessed[" + std::to_string((2 * g) + 1) +
                   "] = " + hex(static_cast<uint256_t>(vk.preprocessed[g].y)) + ";\n";
        }
        out += "            c.proof = " + hex_bytes(exported.proof.to_buffer()) + ";\n";
        const std::vector<FF>& publics = exported.key.public_inputs();
        out += "            c.publicInputs = new uint256[](" + std::to_string(publics.size()) + ");\n";
        for (size_t k = 0; k < publics.size(); ++k) {
            out += "            c.publicInputs[" + std::to_string(k) + "] = " + hex(publics[k]) + ";\n";
        }
        out += "            return c;\n        }\n";
    }

    out += "        revert(\"fixture: no such case\");\n";
    out += "    }\n}\n";
    return out;
}

void write(const std::string& path, const std::string& contents)
{
    std::ofstream file(path);
    file << contents;
    file.close();
    std::cout << "ultra-fflonk-solidity-export: wrote " << path << "\n";
}

} // namespace

int main(int argc, char** argv)
{
    std::string output_dir = "src/barretenberg/ultra_fflonk/solidity/test";
    size_t num_vectors = 8;
    for (int i = 1; i < argc; ++i) {
        const std::string argument = argv[i];
        if (argument == "-o" && i + 1 < argc) {
            output_dir = argv[++i];
        } else if (argument == "--vectors" && i + 1 < argc) {
            num_vectors = static_cast<size_t>(std::stoul(argv[++i]));
        }
    }

    srs::init_file_crs_factory(srs::bb_crs_path());

    write(output_dir + "/RelationVectors.sol", emit_relation_vectors(num_vectors));

    std::vector<ExportedCase> cases;
    const auto add_case = [&](const std::string& label, Builder builder) {
        const auto start = std::chrono::steady_clock::now();
        ProvingKey key = preprocess(builder);
        const auto preprocessed = std::chrono::steady_clock::now();
        Proof proof = prove(key);
        const auto proven = std::chrono::steady_clock::now();
        const bool ok = verify(key.verification_key, proof, key.public_inputs());
        const auto verified = std::chrono::steady_clock::now();

        if (!ok) {
            std::cerr << "ultra-fflonk-solidity-export: refusing to write a proof its own verifier rejects"
                      << "\n";
            std::abort();
        }

        const auto ms = [](auto from, auto to) {
            return static_cast<double>(std::chrono::duration_cast<std::chrono::microseconds>(to - from).count()) /
                   1000.0;
        };
        std::cout << "ultra-fflonk-solidity-export: " << label << ", " << key.circuit_size() << " rows, "
                  << key.public_inputs().size() << " public inputs, proof " << Proof::SIZE_IN_BYTES
                  << " bytes | preprocess " << ms(start, preprocessed) << " ms, prove " << ms(preprocessed, proven)
                  << " ms, verify " << ms(proven, verified) << " ms" << "\n";

        cases.push_back(ExportedCase{ .label = label, .key = std::move(key), .proof = proof });
    };

    add_case("arithmetic", arithmetic_circuit(/*num_public_inputs=*/4, /*num_gates=*/16));
    add_case("every-gate", assorted_circuit());
    add_case("arithmetic-large", arithmetic_circuit(/*num_public_inputs=*/4, /*num_gates=*/6000));

    write(output_dir + "/Fixture.sol", emit_fixture(cases));
    return 0;
}
