// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.21;

import {Test, console} from "forge-std/Test.sol";
import {FflonkVerifier} from "../src/FflonkVerifier.sol";
import {Fixture} from "./Fixture.sol";

/// @dev A no-op with the same signature, to price the external call the measurements wrap.
contract Probe {
    function noop(bytes calldata blob, uint256[] calldata inputs) external pure returns (bool) {
        return blob.length + inputs.length > 0;
    }
}

/**
 * @notice What the wrapper costs on L1, and that the Solidity verifier agrees with the native one.
 *
 * @dev Every fixture is generated by `fflonk_solidity_export_bench`, which verifies the proof with
 * barretenberg's own verifier before writing it out. So a passing acceptance test here is two
 * independent implementations of `PROTOCOL.md` agreeing on the same proof, and each rejection test
 * is both of them rejecting the same tampering.
 */
contract FflonkVerifierTest is Test {
    uint256 internal constant R = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    Probe internal probe;

    function setUp() public {
        probe = new Probe();
    }

    function _deploy(Fixture.Case memory c) internal returns (FflonkVerifier) {
        return new FflonkVerifier(c.circuitSize, c.numPublicInputs, c.omega, c.k1, c.k2, c.c0x, c.c0y);
    }

    // ---------------------------------------------------------------------------------------------
    // Acceptance and cost
    // ---------------------------------------------------------------------------------------------

    function testAcceptsEveryFixture() public {
        for (uint256 i = 0; i < Fixture.COUNT; ++i) {
            Fixture.Case memory c = Fixture.get(i);
            assertTrue(_deploy(c).verify(c.proof, c.publicInputs), "a valid proof was rejected");
        }
    }

    function testGas() public {
        console.log("rows | public inputs | execution gas | calldata gas | transaction gas");
        for (uint256 i = 0; i < Fixture.COUNT; ++i) {
            Fixture.Case memory c = Fixture.get(i);
            FflonkVerifier verifier = _deploy(c);

            // The fixture is in memory, not storage: reading 928 bytes back out of storage would add
            // ~73k of cold SLOADs that a real transaction, whose proof arrives as calldata, never pays.
            uint256 mark = gasleft();
            probe.noop(c.proof, c.publicInputs);
            uint256 overhead = mark - gasleft();

            uint256 before = gasleft();
            bool ok = verifier.verify(c.proof, c.publicInputs);
            uint256 spent = before - gasleft() - overhead;
            assertTrue(ok);

            uint256 calldataGas = _calldataGas(c.proof) + c.publicInputs.length * 32 * 16 + 68 * 16;
            console.log(c.circuitSize, c.publicInputs.length, spent, calldataGas);
            console.log("   transaction gas", 21000 + calldataGas + spent);
        }
    }

    // ---------------------------------------------------------------------------------------------
    // Rejection: the same cases the native suite covers, against the same proofs
    // ---------------------------------------------------------------------------------------------

    function testRejectsATamperedEvaluation() public {
        Fixture.Case memory c = Fixture.get(1);
        FflonkVerifier verifier = _deploy(c);
        for (uint256 i = 0; i < 19; ++i) {
            bytes memory tampered = _copy(c.proof);
            _bump(tampered, 320 + i * 32);
            assertFalse(verifier.verify(tampered, c.publicInputs), "an evaluation is not binding");
        }
    }

    function testRejectsATamperedCommitment() public {
        Fixture.Case memory c = Fixture.get(1);
        FflonkVerifier verifier = _deploy(c);
        for (uint256 i = 0; i < 5; ++i) {
            bytes memory tampered = _copy(c.proof);
            _bump(tampered, i * 64);
            assertFalse(verifier.verify(tampered, c.publicInputs), "a commitment is not binding");
        }
    }

    function testRejectsWrongPublicInputs() public {
        Fixture.Case memory c = Fixture.get(2);
        FflonkVerifier verifier = _deploy(c);
        for (uint256 i = 0; i < c.publicInputs.length; ++i) {
            uint256[] memory tampered = Fixture.get(2).publicInputs;
            tampered[i] += 1;
            assertFalse(verifier.verify(c.proof, tampered), "a public input is not bound");
        }
    }

    function testRejectsAProofForAnotherCircuit() public {
        Fixture.Case memory first = Fixture.get(1);
        Fixture.Case memory second = Fixture.get(2);
        assertFalse(_deploy(second).verify(first.proof, second.publicInputs));
        assertFalse(_deploy(first).verify(second.proof, first.publicInputs));
    }

    function testRejectsAMalformedProof() public {
        Fixture.Case memory c = Fixture.get(1);
        FflonkVerifier verifier = _deploy(c);

        bytes memory truncated = new bytes(c.proof.length - 1);
        for (uint256 i = 0; i < truncated.length; ++i) {
            truncated[i] = c.proof[i];
        }
        assertFalse(verifier.verify(truncated, c.publicInputs));
        assertFalse(verifier.verify(bytes.concat(c.proof, hex"00"), c.publicInputs));
        assertFalse(verifier.verify(new bytes(928), c.publicInputs));

        uint256[] memory tooFew = new uint256[](c.publicInputs.length - 1);
        for (uint256 i = 0; i < tooFew.length; ++i) {
            tooFew[i] = c.publicInputs[i];
        }
        assertFalse(verifier.verify(c.proof, tooFew));
    }

    function testRejectsNonCanonicalEncodings() public {
        Fixture.Case memory c = Fixture.get(1);
        FflonkVerifier verifier = _deploy(c);

        // A scalar at or above the field modulus, which must be rejected rather than reduced.
        bytes memory badScalar = _copy(c.proof);
        for (uint256 i = 0; i < 32; ++i) {
            badScalar[320 + i] = 0xff;
        }
        assertFalse(verifier.verify(badScalar, c.publicInputs));

        // A coordinate at or above the base-field modulus.
        bytes memory badPoint = _copy(c.proof);
        for (uint256 i = 0; i < 32; ++i) {
            badPoint[i] = 0xff;
        }
        assertFalse(verifier.verify(badPoint, c.publicInputs));

        // The point at infinity, encoded as (0, 0).
        bytes memory infinity = _copy(c.proof);
        for (uint256 i = 0; i < 64; ++i) {
            infinity[i] = 0x00;
        }
        assertFalse(verifier.verify(infinity, c.publicInputs));
    }

    function testRejectsSwappedCommitments() public {
        Fixture.Case memory c = Fixture.get(1);
        FflonkVerifier verifier = _deploy(c);

        bytes memory tampered = _copy(c.proof);
        for (uint256 i = 0; i < 64; ++i) {
            (tampered[64 + i], tampered[128 + i]) = (c.proof[128 + i], c.proof[64 + i]);
        }
        assertFalse(verifier.verify(tampered, c.publicInputs));
    }

    function testRejectsAnInvalidVerificationKey() public {
        Fixture.Case memory c = Fixture.get(1);

        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize - 1, c.numPublicInputs, c.omega, c.k1, c.k2, c.c0x, c.c0y);

        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize, c.numPublicInputs, c.omega, c.k1, c.k2, c.c0x, 1);

        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize, c.circuitSize, c.omega, c.k1, c.k2, c.c0x, c.c0y);

        // An omega whose order is not the circuit size: the domain would not be the prover's.
        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize, c.numPublicInputs, 1, c.k1, c.k2, c.c0x, c.c0y);
        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize, c.numPublicInputs, mulmod(c.omega, c.omega, R), c.k1, c.k2, c.c0x, c.c0y);

        // A coset shift inside the domain: distinct wire slots would share a permutation label.
        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize, c.numPublicInputs, c.omega, c.omega, c.k2, c.c0x, c.c0y);
        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize, c.numPublicInputs, c.omega, c.k1, 1, c.c0x, c.c0y);

        // Two shifts in the same coset: k2 = k1 * omega puts k1 H and k2 H on top of each other.
        vm.expectRevert(FflonkVerifier.InvalidVerificationKey.selector);
        new FflonkVerifier(c.circuitSize, c.numPublicInputs, c.omega, c.k1, mulmod(c.k1, c.omega, R), c.c0x, c.c0y);
    }

    /// @dev Any single-byte change anywhere in the proof must be rejected.
    function testFuzzRejectsAnyByteChange(uint256 position, uint8 delta) public {
        Fixture.Case memory c = Fixture.get(1);
        FflonkVerifier verifier = _deploy(c);

        vm.assume(delta != 0);
        bytes memory tampered = _copy(c.proof);
        uint256 index = position % tampered.length;
        tampered[index] = bytes1(uint8(tampered[index]) ^ delta);
        assertFalse(verifier.verify(tampered, c.publicInputs));
    }

    function _copy(bytes memory data) internal pure returns (bytes memory out) {
        out = new bytes(data.length);
        for (uint256 i = 0; i < data.length; ++i) {
            out[i] = data[i];
        }
    }

    /// @dev Add one to the 32-byte word at `offset`.
    function _bump(bytes memory data, uint256 offset) internal pure {
        unchecked {
            for (uint256 i = 32; i > 0; --i) {
                uint8 value = uint8(data[offset + i - 1]);
                data[offset + i - 1] = bytes1(value + 1);
                if (value != 0xff) break;
            }
        }
    }

    function _calldataGas(bytes memory data) internal pure returns (uint256 total) {
        for (uint256 i = 0; i < data.length; ++i) {
            total += data[i] == 0 ? 4 : 16;
        }
    }
}
