#pragma once

#include "../../fields/field.hpp"
#include "../../groups/group.hpp"
#include "../types.hpp"
#include "barretenberg/stdlib/primitives/bigfield/constants.hpp"

// NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays)

/**
 * @file pasta.hpp
 * @brief The Pasta curve cycle (Pallas / Vesta) used by Zcash Orchard and Halo 2.
 *
 * @details
 *   p = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001
 *   q = 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001
 *   Pallas: y^2 = x^3 + 5 over F_p, prime order q.
 *   Vesta:  y^2 = x^3 + 5 over F_q, prime order p.
 *
 * Both moduli are 2^254 + small, so they take barretenberg's "large modulus" field code path (no coarse reduction,
 * no x86 assembly). The generators are (-1, 2) on both curves, matching the pasta_curves crate.
 *
 * Both curves have an efficient endomorphism (x, y) -> (zeta * x, y), and the stored cube roots of unity are paired
 * so that this map equals [cube_root] on both curves. The GLV *scalar splitting* used by barretenberg's MSM assumes
 * 128-bit split halves, which the Pasta lattice basis does not guarantee, so USE_ENDOMORPHISM is false.
 */
namespace bb::pasta {

/**
 * @brief Pallas base field F_p (= Vesta scalar field).
 * @details Generated by pasta_params.py in this directory; see that script for the derivation of every constant.
 * All multi-limb values are little-endian 64-bit (or 29-bit for wasm) limbs. Montgomery-form constants use R = 2^256
 * (R = 2^261 for the wasm variants).
 */
struct FpParams {
    // modulus = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001
    static constexpr uint64_t modulus_0 = 0x992d30ed00000001ULL;
    static constexpr uint64_t modulus_1 = 0x224698fc094cf91bULL;
    static constexpr uint64_t modulus_2 = 0x0ULL;
    static constexpr uint64_t modulus_3 = 0x4000000000000000ULL;
    static constexpr uint64_t r_squared_0 = 0x8c78ecb30000000fULL;
    static constexpr uint64_t r_squared_1 = 0xd7d30dbd8b0de0e7ULL;
    static constexpr uint64_t r_squared_2 = 0x7797a99bc3c95d18ULL;
    static constexpr uint64_t r_squared_3 = 0x96d41af7b9cb714ULL;
    static constexpr uint64_t r_inv = 0x992d30ecffffffffULL;
    static constexpr uint64_t r_inv_0 = 0x311721787d5ec24eULL;
    static constexpr uint64_t r_inv_1 = 0x14823e647de7867cULL;
    static constexpr uint64_t r_inv_2 = 0xc000000000000000ULL;
    static constexpr uint64_t r_inv_3 = 0x264b4c3b3fffffffULL;
    static constexpr uint64_t cube_root_0 = 0x2021cf6619a153dULL;
    static constexpr uint64_t cube_root_1 = 0x9e8c26974980b78eULL;
    static constexpr uint64_t cube_root_2 = 0x2a676d5cc87a4666ULL;
    static constexpr uint64_t cube_root_3 = 0x15d8049da7a17876ULL;
    static constexpr uint64_t primitive_root_0 = 0xa28db849bad6dbf0ULL;
    static constexpr uint64_t primitive_root_1 = 0x9083cd03d3b539dfULL;
    static constexpr uint64_t primitive_root_2 = 0xfba6b9ca9dc8448eULL;
    static constexpr uint64_t primitive_root_3 = 0x3ec928747b89c6daULL;
    static constexpr uint64_t coset_generator_0 = 0xa1a55e68ffffffedULL;
    static constexpr uint64_t coset_generator_1 = 0x74c2a54b4f4982f3ULL;
    static constexpr uint64_t coset_generator_2 = 0xfffffffffffffffdULL;
    static constexpr uint64_t coset_generator_3 = 0x3fffffffffffffffULL;
    static constexpr uint64_t modulus_wasm_0 = 0x1;
    static constexpr uint64_t modulus_wasm_1 = 0x9698768;
    static constexpr uint64_t modulus_wasm_2 = 0x133e46e6;
    static constexpr uint64_t modulus_wasm_3 = 0xd31f812;
    static constexpr uint64_t modulus_wasm_4 = 0x224;
    static constexpr uint64_t modulus_wasm_5 = 0x0;
    static constexpr uint64_t modulus_wasm_6 = 0x0;
    static constexpr uint64_t modulus_wasm_7 = 0x0;
    static constexpr uint64_t modulus_wasm_8 = 0x400000;
    static constexpr uint64_t r_squared_wasm_0 = 0x2338212200003b6aULL;
    static constexpr uint64_t r_squared_wasm_1 = 0x36d9527ec469a806ULL;
    static constexpr uint64_t r_squared_wasm_2 = 0x5ea66f0f2574634bULL;
    static constexpr uint64_t r_squared_wasm_3 = 0x3506bdee72dc51deULL;
    static constexpr uint64_t r_inv_wasm_0 = 0x16967899;
    static constexpr uint64_t r_inv_wasm_1 = 0x162b4081;
    static constexpr uint64_t r_inv_wasm_2 = 0x60c4ed3;
    static constexpr uint64_t r_inv_wasm_3 = 0xd31f5ee;
    static constexpr uint64_t r_inv_wasm_4 = 0x224;
    static constexpr uint64_t r_inv_wasm_5 = 0x0;
    static constexpr uint64_t r_inv_wasm_6 = 0x0;
    static constexpr uint64_t r_inv_wasm_7 = 0x1fc00000;
    static constexpr uint64_t r_inv_wasm_8 = 0x3fffff;
    static constexpr uint64_t cube_root_wasm_0 = 0x447fb58a3342a796ULL;
    static constexpr uint64_t cube_root_wasm_1 = 0x7ac2d910d31536acULL;
    static constexpr uint64_t cube_root_wasm_2 = 0x4cedab990f48ccd2ULL;
    static constexpr uint64_t cube_root_wasm_3 = 0x3b0093b4f42f0ec5ULL;
    static constexpr uint64_t primitive_root_wasm_0 = 0xc53e1c845adb7de1ULL;
    static constexpr uint64_t primitive_root_wasm_1 = 0xe9ed19f55655119cULL;
    static constexpr uint64_t primitive_root_wasm_2 = 0x74d73953b90891cdULL;
    static constexpr uint64_t primitive_root_wasm_3 = 0x19250e8f7138db5fULL;
    static constexpr uint64_t coset_generator_wasm_0 = 0xa832e06cfffffd81ULL;
    static constexpr uint64_t coset_generator_wasm_1 = 0x71c822e4c8de341cULL;
    static constexpr uint64_t coset_generator_wasm_2 = 0xffffffffffffffaaULL;
    static constexpr uint64_t coset_generator_wasm_3 = 0x3fffffffffffffffULL;
    static constexpr uint64_t endo_g1_lo = 0;
    static constexpr uint64_t endo_g1_mid = 0;
    static constexpr uint64_t endo_g1_hi = 0;
    static constexpr uint64_t endo_g2_lo = 0;
    static constexpr uint64_t endo_g2_mid = 0;
    static constexpr uint64_t endo_minus_b1_lo = 0;
    static constexpr uint64_t endo_minus_b1_mid = 0;
    static constexpr uint64_t endo_b2_lo = 0;
    static constexpr uint64_t endo_b2_mid = 0;
    // 2-adicity = 32

    static constexpr char schema_name[] = "pasta_fp";
    // Both Pasta fields have 2-adicity 32, which is enough for barretenberg's FFT helpers.
    static constexpr bool has_high_2adicity = true;
    static constexpr size_t PUBLIC_INPUTS_SIZE = BIGFIELD_PUBLIC_INPUTS_SIZE;
};

/**
 * @brief Pallas scalar field F_q (= Vesta base field).
 * @details Generated by pasta_params.py in this directory; see that script for the derivation of every constant.
 * All multi-limb values are little-endian 64-bit (or 29-bit for wasm) limbs. Montgomery-form constants use R = 2^256
 * (R = 2^261 for the wasm variants).
 */
struct FqParams {
    // modulus = 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001
    static constexpr uint64_t modulus_0 = 0x8c46eb2100000001ULL;
    static constexpr uint64_t modulus_1 = 0x224698fc0994a8ddULL;
    static constexpr uint64_t modulus_2 = 0x0ULL;
    static constexpr uint64_t modulus_3 = 0x4000000000000000ULL;
    static constexpr uint64_t r_squared_0 = 0xfc9678ff0000000fULL;
    static constexpr uint64_t r_squared_1 = 0x67bb433d891a16e3ULL;
    static constexpr uint64_t r_squared_2 = 0x7fae231004ccf590ULL;
    static constexpr uint64_t r_squared_3 = 0x96d41af7ccfdaa9ULL;
    static constexpr uint64_t r_inv = 0x8c46eb20ffffffffULL;
    static constexpr uint64_t r_inv_0 = 0xe631af527c6cf164ULL;
    static constexpr uint64_t r_inv_1 = 0x12c81a72e3b10047ULL;
    static constexpr uint64_t r_inv_2 = 0xc000000000000000ULL;
    static constexpr uint64_t r_inv_3 = 0x2311bac83fffffffULL;
    static constexpr uint64_t cube_root_0 = 0x7c541a8480111122ULL;
    static constexpr uint64_t cube_root_1 = 0x40630b9c56ed29daULL;
    static constexpr uint64_t cube_root_2 = 0x2c275fb135b2b29ULL;
    static constexpr uint64_t cube_root_3 = 0x121d29f888245b10ULL;
    static constexpr uint64_t primitive_root_0 = 0x218077428c9942deULL;
    static constexpr uint64_t primitive_root_1 = 0xcc49578921b60494ULL;
    static constexpr uint64_t primitive_root_2 = 0xac2e5d27b2efbee2ULL;
    static constexpr uint64_t primitive_root_3 = 0xb79fa897f2db056ULL;
    static constexpr uint64_t coset_generator_0 = 0x96bc8c8cffffffedULL;
    static constexpr uint64_t coset_generator_1 = 0x74c2a54b49f7778eULL;
    static constexpr uint64_t coset_generator_2 = 0xfffffffffffffffdULL;
    static constexpr uint64_t coset_generator_3 = 0x3fffffffffffffffULL;
    static constexpr uint64_t modulus_wasm_0 = 0x1;
    static constexpr uint64_t modulus_wasm_1 = 0x2375908;
    static constexpr uint64_t modulus_wasm_2 = 0x52a3763;
    static constexpr uint64_t modulus_wasm_3 = 0xd31f813;
    static constexpr uint64_t modulus_wasm_4 = 0x224;
    static constexpr uint64_t modulus_wasm_5 = 0x0;
    static constexpr uint64_t modulus_wasm_6 = 0x0;
    static constexpr uint64_t modulus_wasm_7 = 0x0;
    static constexpr uint64_t modulus_wasm_8 = 0x400000;
    static constexpr uint64_t r_squared_wasm_0 = 0x285636aa00003b6aULL;
    static constexpr uint64_t r_squared_wasm_1 = 0xd7af5276cb409e22ULL;
    static constexpr uint64_t r_squared_wasm_2 = 0xb88c401333d6418aULL;
    static constexpr uint64_t r_squared_wasm_3 = 0x3506bdf33f6aa5feULL;
    static constexpr uint64_t r_inv_wasm_0 = 0x1dc8a6f9;
    static constexpr uint64_t r_inv_wasm_1 = 0x1d0d21a4;
    static constexpr uint64_t r_inv_wasm_2 = 0x17f83f4f;
    static constexpr uint64_t r_inv_wasm_3 = 0xd31f5ee;
    static constexpr uint64_t r_inv_wasm_4 = 0x224;
    static constexpr uint64_t r_inv_wasm_5 = 0x0;
    static constexpr uint64_t r_inv_wasm_6 = 0x0;
    static constexpr uint64_t r_inv_wasm_7 = 0x1fc00000;
    static constexpr uint64_t r_inv_wasm_8 = 0x3fffff;
    static constexpr uint64_t cube_root_wasm_0 = 0x9c050c6702222437ULL;
    static constexpr uint64_t cube_root_wasm_1 = 0xd7e612ae876b4b85ULL;
    static constexpr uint64_t cube_root_wasm_2 = 0x584ebf626b656526ULL;
    static constexpr uint64_t cube_root_wasm_3 = 0x3a53f11048b6200ULL;
    static constexpr uint64_t primitive_root_wasm_0 = 0x72ac50ac93285bbbULL;
    static constexpr uint64_t primitive_root_wasm_1 = 0xddc9f43806d94630ULL;
    static constexpr uint64_t primitive_root_wasm_2 = 0x85cba4f65df7dc58ULL;
    static constexpr uint64_t primitive_root_wasm_3 = 0x2f3f512fe5b60ad5ULL;
    static constexpr uint64_t coset_generator_wasm_0 = 0xdafb18a0fffffd81ULL;
    static constexpr uint64_t coset_generator_wasm_1 = 0x71c822e415ee7efeULL;
    static constexpr uint64_t coset_generator_wasm_2 = 0xffffffffffffffaaULL;
    static constexpr uint64_t coset_generator_wasm_3 = 0x3fffffffffffffffULL;
    static constexpr uint64_t endo_g1_lo = 0;
    static constexpr uint64_t endo_g1_mid = 0;
    static constexpr uint64_t endo_g1_hi = 0;
    static constexpr uint64_t endo_g2_lo = 0;
    static constexpr uint64_t endo_g2_mid = 0;
    static constexpr uint64_t endo_minus_b1_lo = 0;
    static constexpr uint64_t endo_minus_b1_mid = 0;
    static constexpr uint64_t endo_b2_lo = 0;
    static constexpr uint64_t endo_b2_mid = 0;
    // 2-adicity = 32

    static constexpr char schema_name[] = "pasta_fq";
    // Both Pasta fields have 2-adicity 32, which is enough for barretenberg's FFT helpers.
    static constexpr bool has_high_2adicity = true;
    static constexpr size_t PUBLIC_INPUTS_SIZE = BIGFIELD_PUBLIC_INPUTS_SIZE;
};

using fp = field<FpParams>;
using fq = field<FqParams>;

} // namespace bb::pasta

namespace bb::pallas {

using fq = bb::pasta::fp; // base field
using fr = bb::pasta::fq; // scalar field

struct G1Params {
    static constexpr bool USE_ENDOMORPHISM = false;
    static constexpr bool can_hash_to_curve = true;
    static constexpr bool has_a = false;
    static constexpr fq b = fq(5);
    static constexpr fq a = fq(0);
    // generator (-1, 2)
    static constexpr fq one_x = fq(bb::pasta::FpParams::modulus_0 - 1,
                                   bb::pasta::FpParams::modulus_1,
                                   bb::pasta::FpParams::modulus_2,
                                   bb::pasta::FpParams::modulus_3)
                                    .to_montgomery_form();
    static constexpr fq one_y = fq(2);
};
using g1 = group<fq, fr, G1Params>;

inline std::string msgpack_schema_name(g1::affine_element const& /*unused*/)
{
    return "PallasPoint";
}

} // namespace bb::pallas

namespace bb::vesta {

using fq = bb::pasta::fq; // base field
using fr = bb::pasta::fp; // scalar field

struct G1Params {
    static constexpr bool USE_ENDOMORPHISM = false;
    static constexpr bool can_hash_to_curve = true;
    static constexpr bool has_a = false;
    static constexpr fq b = fq(5);
    static constexpr fq a = fq(0);
    // generator (-1, 2)
    static constexpr fq one_x = fq(bb::pasta::FqParams::modulus_0 - 1,
                                   bb::pasta::FqParams::modulus_1,
                                   bb::pasta::FqParams::modulus_2,
                                   bb::pasta::FqParams::modulus_3)
                                    .to_montgomery_form();
    static constexpr fq one_y = fq(2);
};
using g1 = group<fq, fr, G1Params>;

inline std::string msgpack_schema_name(g1::affine_element const& /*unused*/)
{
    return "VestaPoint";
}

} // namespace bb::vesta

namespace bb::curve {

/**
 * @brief Pallas: the embedded curve of circuits over F_p (Orchard's "inner" curve).
 */
class Pallas {
  public:
    using ScalarField = bb::pallas::fr;
    using BaseField = bb::pallas::fq;
    using Group = bb::pallas::g1;
    using Element = typename Group::element;
    using AffineElement = typename Group::affine_element;

    static constexpr const char* name = "Pallas";
    static constexpr bool is_stdlib_type = false;

    // Order-256 subgroup of F_q^*, generated by 5^((q - 1) / 256), for SmallSubgroupIPA.
    static constexpr size_t SUBGROUP_SIZE = 256;
    static constexpr ScalarField subgroup_generator =
        ScalarField(uint256_t("0x0a81955d1b842bf9baa32f613be2e8a90afad96d7d4dabe3fb0d5b1b6b26f170"));
    static constexpr ScalarField subgroup_generator_inverse =
        ScalarField(uint256_t("0x05114db9e3ded08ea01ffdabe9e0d719fac8758d08bb2da16408cc1e65faeb71"));
    static constexpr uint32_t LIBRA_UNIVARIATES_LENGTH = 9;
};

/**
 * @brief Vesta: the commitment curve for circuits over F_p (Halo 2 commits Orchard proofs on Vesta).
 */
class Vesta {
  public:
    using ScalarField = bb::vesta::fr;
    using BaseField = bb::vesta::fq;
    using Group = bb::vesta::g1;
    using Element = typename Group::element;
    using AffineElement = typename Group::affine_element;

    static constexpr const char* name = "Vesta";
    static constexpr bool is_stdlib_type = false;

    // Order-256 subgroup of F_p^*, generated by 5^((p - 1) / 256), for SmallSubgroupIPA.
    static constexpr size_t SUBGROUP_SIZE = 256;
    static constexpr ScalarField subgroup_generator =
        ScalarField(uint256_t("0x21d0b0a3be45b5ee2ff5140e6007a63bc5ac7dc51c50ed52ebf2f918f4d603c9"));
    static constexpr ScalarField subgroup_generator_inverse =
        ScalarField(uint256_t("0x11f949260a7860af3a48fc447836cebe94e941f2a38afe4f78eb82219e749411"));
    static constexpr uint32_t LIBRA_UNIVARIATES_LENGTH = 9;
};

} // namespace bb::curve

// NOLINTEND(cppcoreguidelines-avoid-c-arrays)
