// AUTOGENERATED FILE - do not edit. Regenerate with:
//   barretenberg/cpp/src/barretenberg/ultra_fflonk/solidity/generate_contract_header.sh
//
// The verifier source of truth is barretenberg/cpp/src/barretenberg/ultra_fflonk/solidity/src/,
// which is what the Foundry suite there tests. This header is those files flattened into one
// translation unit, so that `bb write_solidity_verifier --scheme ultra_fflonk` can emit a
// self-contained contract.
#pragma once

#include <string_view>

namespace bb {

static constexpr std::string_view ULTRA_FFLONK_VERIFIER_SOURCE = R"CONTRACT(
// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.21;

// ----- src/UltraFflonkTypes.sol -----

/**
 * @title The entity layout and relation parameters the Ultra relation set reads.
 *
 * @dev The indices are `flavor/generated/ultra_flavor_generated.hpp`'s `EntityId`, verbatim. They are
 * protocol: the prover packs its groups in this order and the verifier reassembles the row from the
 * proof's evaluations into an array with this layout, so a reordering here is a reordering of the
 * proof.
 */
library UltraFflonkTypes {
    /// BN254 scalar field.
    uint256 internal constant R = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    uint256 internal constant NUM_ENTITIES = 41;

    // Precomputed (0 .. 27).
    uint256 internal constant E_SIGMA_1 = 0;
    uint256 internal constant E_SIGMA_2 = 1;
    uint256 internal constant E_SIGMA_3 = 2;
    uint256 internal constant E_SIGMA_4 = 3;
    uint256 internal constant E_ID_1 = 4;
    uint256 internal constant E_ID_2 = 5;
    uint256 internal constant E_ID_3 = 6;
    uint256 internal constant E_ID_4 = 7;
    uint256 internal constant E_LAGRANGE_FIRST = 8;
    uint256 internal constant E_LAGRANGE_LAST = 9;
    uint256 internal constant E_Q_LOOKUP = 10;
    uint256 internal constant E_TABLE_1 = 11;
    uint256 internal constant E_TABLE_2 = 12;
    uint256 internal constant E_TABLE_3 = 13;
    uint256 internal constant E_TABLE_4 = 14;
    uint256 internal constant E_Q_M = 15;
    uint256 internal constant E_Q_R = 16;
    uint256 internal constant E_Q_O = 17;
    uint256 internal constant E_Q_C = 18;
    uint256 internal constant E_Q_L = 19;
    uint256 internal constant E_Q_4 = 20;
    uint256 internal constant E_Q_ARITH = 21;
    uint256 internal constant E_Q_DELTA_RANGE = 22;
    uint256 internal constant E_Q_ELLIPTIC = 23;
    uint256 internal constant E_Q_MEMORY = 24;
    uint256 internal constant E_Q_NNF = 25;
    uint256 internal constant E_Q_POSEIDON2_EXTERNAL = 26;
    uint256 internal constant E_Q_POSEIDON2_INTERNAL = 27;

    // Witness (28 .. 35).
    uint256 internal constant E_W_L = 28;
    uint256 internal constant E_W_R = 29;
    uint256 internal constant E_W_O = 30;
    uint256 internal constant E_W_4 = 31;
    uint256 internal constant E_Z_PERM = 32;
    uint256 internal constant E_LOOKUP_INVERSES = 33;
    uint256 internal constant E_LOOKUP_READ_COUNTS = 34;
    uint256 internal constant E_LOOKUP_READ_TAGS = 35;

    // Shifted (36 .. 40): the same column read at the next row.
    uint256 internal constant E_W_L_SHIFT = 36;
    uint256 internal constant E_W_R_SHIFT = 37;
    uint256 internal constant E_W_O_SHIFT = 38;
    uint256 internal constant E_W_4_SHIFT = 39;
    uint256 internal constant E_Z_PERM_SHIFT = 40;

    /**
     * @dev `RelationParameters<FF>`, restricted to the fields the Ultra set reads. `beta_quartic` and
     * the Translator/ECCVM fields are not used by any relation here and are therefore absent.
     */
    struct Params {
        uint256 eta;
        uint256 etaTwo;
        uint256 etaThree;
        uint256 romLogupGamma;
        uint256 beta;
        uint256 gamma;
        uint256 publicInputDelta;
        uint256 betaSqr;
        uint256 betaCube;
    }
}

// ----- src/relations/PermutationRelation.sol -----


/// @dev Port of relations/permutation_relation.hpp — the copy-constraint grand product over the four wires.
library PermutationRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[3] memory out) internal pure {
        // (0) Grand product construction: the running product advances by the ratio of the id-labelled
        // wire tuple to the sigma-permuted one. `lagrange_first` seeds the product at the first row
        // (where z_perm is constrained to 0 by subrelation (2), making the factor 1), and the
        // public-input delta closes it at the last row.
        {
            uint256 left = mulmod(
                addmod(e[UltraFflonkTypes.E_Z_PERM], e[UltraFflonkTypes.E_LAGRANGE_FIRST], R), numerator(e, p), R
            );

            uint256 publicInputTerm = addmod(
                mulmod(e[UltraFflonkTypes.E_LAGRANGE_LAST], p.publicInputDelta, R),
                e[UltraFflonkTypes.E_Z_PERM_SHIFT],
                R
            );

            out[0] = addmod(left, R - mulmod(publicInputTerm, denominator(e, p), R), R);
        }

        // (1) Left-shiftability: z_perm must vanish immediately after the last active row.
        out[1] = mulmod(e[UltraFflonkTypes.E_LAGRANGE_LAST], e[UltraFflonkTypes.E_Z_PERM_SHIFT], R);

        // (2) Initialization: z_perm is 0 at the first row, so that (z_perm + L_first) starts the
        // product at 1. Without it a prover could pick an arbitrary starting value.
        out[2] = mulmod(e[UltraFflonkTypes.E_LAGRANGE_FIRST], e[UltraFflonkTypes.E_Z_PERM], R);
    }

    /// @dev Grand product numerator: the wires tagged by their own row identity, prod_i (w_i + id_i*beta + gamma).
    function numerator(uint256[41] memory e, UltraFflonkTypes.Params memory p) private pure returns (uint256) {
        uint256 acc;
        {
            uint256 t1 =
                addmod(mulmod(e[UltraFflonkTypes.E_ID_1], p.beta, R), addmod(e[UltraFflonkTypes.E_W_L], p.gamma, R), R);
            uint256 t2 =
                addmod(mulmod(e[UltraFflonkTypes.E_ID_2], p.beta, R), addmod(e[UltraFflonkTypes.E_W_R], p.gamma, R), R);
            acc = mulmod(t1, t2, R);
        }
        {
            uint256 t3 =
                addmod(mulmod(e[UltraFflonkTypes.E_ID_3], p.beta, R), addmod(e[UltraFflonkTypes.E_W_O], p.gamma, R), R);
            uint256 t4 =
                addmod(mulmod(e[UltraFflonkTypes.E_ID_4], p.beta, R), addmod(e[UltraFflonkTypes.E_W_4], p.gamma, R), R);
            acc = mulmod(acc, mulmod(t3, t4, R), R);
        }
        return acc;
    }

    /// @dev Grand product denominator: the same wires tagged by their permutation image,
    /// prod_i (w_i + sigma_i*beta + gamma).
    function denominator(uint256[41] memory e, UltraFflonkTypes.Params memory p) private pure returns (uint256) {
        uint256 acc;
        {
            uint256 t5 = addmod(
                mulmod(e[UltraFflonkTypes.E_SIGMA_1], p.beta, R), addmod(e[UltraFflonkTypes.E_W_L], p.gamma, R), R
            );
            uint256 t6 = addmod(
                mulmod(e[UltraFflonkTypes.E_SIGMA_2], p.beta, R), addmod(e[UltraFflonkTypes.E_W_R], p.gamma, R), R
            );
            acc = mulmod(t5, t6, R);
        }
        {
            uint256 t7 = addmod(
                mulmod(e[UltraFflonkTypes.E_SIGMA_3], p.beta, R), addmod(e[UltraFflonkTypes.E_W_O], p.gamma, R), R
            );
            uint256 t8 = addmod(
                mulmod(e[UltraFflonkTypes.E_SIGMA_4], p.beta, R), addmod(e[UltraFflonkTypes.E_W_4], p.gamma, R), R
            );
            acc = mulmod(acc, mulmod(t7, t8, R), R);
        }
        return acc;
    }
}

// ----- src/relations/LogDerivLookupRelation.sol -----


/// @dev Port of relations/logderiv_lookup_relation.hpp — the log-derivative lookup argument: reads
/// from a table of up to three columns, expressed as a sum of inverses of the read and table terms.
library LogDerivLookupRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[3] memory out) internal pure {
        uint256 tableTerm = computeTableTerm(e, p);
        uint256 lookupTerm = computeLookupTerm(e, p);
        uint256 inverses = e[UltraFflonkTypes.E_LOOKUP_INVERSES];

        // Subrelation 0: the polynomial of inverses I is correctly formed, i.e.
        // I * lookup_term * table_term == inverse_exists. The right-hand side rather than 1 because I
        // is set to 0 on rows that neither perform a read nor hold read table data.
        {
            uint256 readTags = e[UltraFflonkTypes.E_LOOKUP_READ_TAGS];
            uint256 readSelector = e[UltraFflonkTypes.E_Q_LOOKUP];
            // inverse_exists = 1 - (1 - read_tag) * (1 - is_read_gate), expanded assuming both are boolean
            uint256 inverseExists = addmod(addmod(readTags, readSelector, R), R - mulmod(readTags, readSelector, R), R);
            uint256 product = mulmod(mulmod(lookupTerm, tableTerm, R), inverses, R);
            out[0] = addmod(product, R - inverseExists, R);
        }

        // Subrelation 1: the lookup identity itself. Summed over the trace this is
        // sum(q_lookup / lookup_term - read_count / table_term), rearranged over the common
        // denominator I = 1 / (lookup_term * table_term). Linearly dependent: it only vanishes when
        // aggregated across all rows, not row by row.
        {
            uint256 readSelector = e[UltraFflonkTypes.E_Q_LOOKUP];
            uint256 readCounts = e[UltraFflonkTypes.E_LOOKUP_READ_COUNTS];
            uint256 tmp = addmod(mulmod(readSelector, tableTerm, R), R - mulmod(readCounts, lookupTerm, R), R);
            out[1] = mulmod(tmp, inverses, R);
        }

        // Subrelation 2: read_tag is boolean. Required because inverse_exists above is only the
        // intended OR when read_tag is constrained to {0, 1}; otherwise a prover could pick any value
        // for it on rows where the read selector is off.
        {
            uint256 readTag = e[UltraFflonkTypes.E_LOOKUP_READ_TAGS];
            out[2] = addmod(mulmod(readTag, readTag, R), R - readTag, R);
        }
    }

    /// @dev table_1 + gamma + table_2 * beta + table_3 * beta^2 + table_4 * beta^3, where table_1..3
    /// are the lookup table's columns and table_4 is the table's unique identifier.
    function computeTableTerm(uint256[41] memory e, UltraFflonkTypes.Params memory p)
        private
        pure
        returns (uint256 result)
    {
        result = mulmod(e[UltraFflonkTypes.E_TABLE_2], p.beta, R);
        result = addmod(result, mulmod(e[UltraFflonkTypes.E_TABLE_3], p.betaSqr, R), R);
        result = addmod(result, mulmod(e[UltraFflonkTypes.E_TABLE_4], p.betaCube, R), R);
        result = addmod(result, e[UltraFflonkTypes.E_TABLE_1], R);
        result = addmod(result, p.gamma, R);
    }

    /// @dev The read term, built from the same challenge powers as the table term. The looked-up
    /// values are not the wires themselves: wires hold successive accumulators, and column i's entry
    /// is recovered as w_i + (negated step size) * w_i_shift. The step sizes live in q_r/q_m/q_c and
    /// the table identifier in q_o.
    function computeLookupTerm(uint256[41] memory e, UltraFflonkTypes.Params memory p)
        private
        pure
        returns (uint256 result)
    {
        uint256 derivedEntry2 = addmod(
            mulmod(e[UltraFflonkTypes.E_Q_M], e[UltraFflonkTypes.E_W_R_SHIFT], R), e[UltraFflonkTypes.E_W_R], R
        );
        uint256 derivedEntry3 =
            addmod(mulmod(e[UltraFflonkTypes.E_Q_C], e[UltraFflonkTypes.E_W_O_SHIFT], R), e[UltraFflonkTypes.E_W_O], R);

        result = addmod(mulmod(derivedEntry2, p.beta, R), mulmod(derivedEntry3, p.betaSqr, R), R);

        {
            uint256 derivedEntry1 = addmod(
                mulmod(e[UltraFflonkTypes.E_Q_R], e[UltraFflonkTypes.E_W_L_SHIFT], R),
                addmod(e[UltraFflonkTypes.E_W_L], p.gamma, R),
                R
            );
            uint256 tableIndexEntry = mulmod(e[UltraFflonkTypes.E_Q_O], p.betaCube, R);
            result = addmod(result, addmod(derivedEntry1, tableIndexEntry, R), R);
        }
    }
}

// ----- src/relations/ArithmeticRelation.sol -----


/// @dev Port of relations/ultra_arithmetic_relation.hpp — the width-4 Ultra arithmetic gate, whose
/// two subrelations encode four different identities selected by q_arith in {0, 1, 2, 3}.
library ArithmeticRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// -1/2 in the BN254 scalar field: the C++ `FF(-2).invert()`, i.e. (R - 1) / 2.
    /// It rescales the multiplicative term so that (q_arith - 3) * q_m * (-1/2) equals q_m at
    /// q_arith == 1, twice q_m at q_arith == 2, and vanishes at q_arith == 3.
    uint256 internal constant NEG_HALF = 0x183227397098d014dc2822db40c0ac2e9419f4243cdcb848a1f0fac9f8000000;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[2] memory out) internal pure {
        p; // this relation reads no relation parameters

        uint256 qArith = e[UltraFflonkTypes.E_Q_ARITH];
        // (q_arith - 1) gates the extra w_4_shift term in the first subrelation and, together with
        // q_arith itself, disables the second subrelation for q_arith in {0, 1}.
        uint256 qArithSub1 = addmod(qArith, R - 1, R);

        // Subrelation 0: the gate identity itself. The whole expression is scaled by q_arith, so it
        // is vacuous on rows where the arithmetic gate is switched off.
        {
            uint256 acc;
            // Multiplicative term q_m * w_l * w_r, weighted by (-1/2) * (q_arith - 3).
            {
                uint256 mulTerm = mulmod(mulmod(e[UltraFflonkTypes.E_W_R], e[UltraFflonkTypes.E_W_L], R), NEG_HALF, R);
                uint256 qmWeight = mulmod(addmod(qArith, R - 3, R), e[UltraFflonkTypes.E_Q_M], R);
                acc = mulmod(mulTerm, qmWeight, R);
            }
            // Linear terms sum_{i in {l, r, o, 4}} q_i * w_i plus the constant selector.
            {
                uint256 lin = mulmod(e[UltraFflonkTypes.E_Q_L], e[UltraFflonkTypes.E_W_L], R);
                lin = addmod(lin, mulmod(e[UltraFflonkTypes.E_Q_R], e[UltraFflonkTypes.E_W_R], R), R);
                lin = addmod(lin, mulmod(e[UltraFflonkTypes.E_Q_O], e[UltraFflonkTypes.E_W_O], R), R);
                lin = addmod(lin, mulmod(e[UltraFflonkTypes.E_Q_4], e[UltraFflonkTypes.E_W_4], R), R);
                lin = addmod(lin, e[UltraFflonkTypes.E_Q_C], R);
                // Carry from the next row, enabled only for q_arith >= 2.
                lin = addmod(lin, mulmod(qArithSub1, e[UltraFflonkTypes.E_W_4_SHIFT], R), R);
                acc = addmod(acc, lin, R);
            }
            out[0] = mulmod(acc, qArith, R);
        }

        // Subrelation 1: active only at q_arith == 3, where q_m is repurposed as an additive term
        // and w_l_shift is constrained to w_l + w_4 + q_m.
        {
            uint256 sum = addmod(e[UltraFflonkTypes.E_W_L], e[UltraFflonkTypes.E_W_4], R);
            sum = addmod(sum, R - e[UltraFflonkTypes.E_W_L_SHIFT], R);
            sum = addmod(sum, e[UltraFflonkTypes.E_Q_M], R);

            uint256 gate = mulmod(sum, addmod(qArith, R - 2, R), R);
            out[1] = mulmod(gate, mulmod(qArithSub1, qArith, R), R);
        }
    }
}

// ----- src/relations/DeltaRangeRelation.sol -----


/// @dev Port of relations/delta_range_constraint_relation.hpp — each of the four consecutive wire
/// differences across the row (and into the next row) lies in {0, 1, 2, 3}, which is what makes the
/// sorted-witness range check work.
library DeltaRangeRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[4] memory out) internal pure {
        uint256 qDeltaRange = e[UltraFflonkTypes.E_Q_DELTA_RANGE];

        // Subrelation 0: D_0 = w_2 - w_1 is in {0,1,2,3}.
        {
            uint256 delta = addmod(e[UltraFflonkTypes.E_W_R], R - e[UltraFflonkTypes.E_W_L], R);
            out[0] = gatedRangeCheck(delta, qDeltaRange);
        }

        // Subrelation 1: D_1 = w_3 - w_2 is in {0,1,2,3}.
        {
            uint256 delta = addmod(e[UltraFflonkTypes.E_W_O], R - e[UltraFflonkTypes.E_W_R], R);
            out[1] = gatedRangeCheck(delta, qDeltaRange);
        }

        // Subrelation 2: D_2 = w_4 - w_3 is in {0,1,2,3}.
        {
            uint256 delta = addmod(e[UltraFflonkTypes.E_W_4], R - e[UltraFflonkTypes.E_W_O], R);
            out[2] = gatedRangeCheck(delta, qDeltaRange);
        }

        // Subrelation 3: D_3 = w_1_shift - w_4 links this row's last wire to the next row's first.
        {
            uint256 delta = addmod(e[UltraFflonkTypes.E_W_L_SHIFT], R - e[UltraFflonkTypes.E_W_4], R);
            out[3] = gatedRangeCheck(delta, qDeltaRange);
        }

        p; // the relation reads no relation parameters
    }

    /// @dev q * D(D-1)(D-2)(D-3), evaluated via the identity T*(T+2) == D(D-1)(D-2)(D-3) for T = (D-3)*D.
    function gatedRangeCheck(uint256 delta, uint256 qDeltaRange) private pure returns (uint256) {
        uint256 t = mulmod(addmod(delta, R - 3, R), delta, R);
        return mulmod(mulmod(t, addmod(t, 2, R), R), qDeltaRange, R);
    }
}

// ----- src/relations/EllipticRelation.sol -----


/// @dev Port of relations/elliptic_relation.hpp — short-Weierstrass point addition/subtraction and
/// doubling: given P1 = (x1, y1) and P2 = (x2, y2), constrains P3 = P1 ± P2, or P3 = 2*P1.
library EllipticRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// Curve constant `b` of the embedded curve, i.e. `EllipticRelationImpl::get_curve_b()`.
    /// The Ultra flavor's FF is the BN254 scalar field, which equals `grumpkin::fq`, so the
    /// second branch is taken and this is `grumpkin::g1::curve_b`. That value is stored in
    /// grumpkin.hpp as Montgomery-form limbs {0xdd7056026000005a, 0x223fa97acb319311,
    /// 0xcc388229877910c0, 0x34394632b724eaa}; converting out of Montgomery form gives R - 17,
    /// matching the Grumpkin curve equation y^2 = x^3 - 17.
    uint256 internal constant CURVE_B = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593effffff0;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory, uint256[2] memory out) internal pure {
        out[0] = xCoordinate(e);
        out[1] = yCoordinate(e);
    }

    /// @dev Subrelation 0: the x-coordinate of P3. The addition branch enforces
    /// (x3 + x2 + x1)(x2 - x1)^2 - (y2^2 + y1^2 - 2*q_sign*y2*y1) = 0, the cleared-denominator form of
    /// x3 = lambda^2 - x1 - x2. The doubling branch enforces (x3 + 2*x1)*4*y1^2 - 9*x1*(y1^2 - b) = 0,
    /// which uses the on-curve identity x1^3 = y1^2 - b to keep the degree down. The two branches are
    /// selected by q_elliptic*(1 - q_is_double) and q_elliptic*q_is_double respectively.
    function xCoordinate(uint256[41] memory e) private pure returns (uint256) {
        uint256 x1 = e[UltraFflonkTypes.E_W_R];
        uint256 y1 = e[UltraFflonkTypes.E_W_O];
        uint256 y1Sqr = mulmod(y1, y1, R);
        uint256 x1Mul3 = addmod(x1, addmod(x1, x1, R), R);

        // (x3 - x1), (x3 + 2*x1) and (x3 + x2 + x1), built up from the shifted wires.
        uint256 x2SubX1 = addmod(e[UltraFflonkTypes.E_W_L_SHIFT], R - x1, R);
        uint256 x3PlusTwoX1 = addmod(addmod(e[UltraFflonkTypes.E_W_R_SHIFT], R - x1, R), x1Mul3, R);
        uint256 x3PlusX2PlusX1 = addmod(x3PlusTwoX1, x2SubX1, R);

        uint256 xAddIdentity;
        {
            uint256 y2 = e[UltraFflonkTypes.E_W_4_SHIFT];
            uint256 y2MulQSign = mulmod(y2, e[UltraFflonkTypes.E_Q_L], R);
            uint256 acc = mulmod(x3PlusX2PlusX1, mulmod(x2SubX1, x2SubX1, R), R);
            acc = addmod(acc, R - addmod(mulmod(y2, y2, R), y1Sqr, R), R);
            xAddIdentity = addmod(acc, mulmod(addmod(y2MulQSign, y2MulQSign, R), y1, R), R);
        }

        uint256 xDoubleIdentity;
        {
            // 3*x1*(y1^2 - b) stands in for 3*x1^4; tripling it gives the 9*x1^4 term.
            uint256 xPow4Mul3 = mulmod(addmod(y1Sqr, R - CURVE_B, R), x1Mul3, R);
            uint256 x1Pow4Mul9 = addmod(xPow4Mul3, addmod(xPow4Mul3, xPow4Mul3, R), R);
            uint256 y1SqrMul4 = addmod(y1Sqr, y1Sqr, R);
            y1SqrMul4 = addmod(y1SqrMul4, y1SqrMul4, R);
            xDoubleIdentity = addmod(mulmod(x3PlusTwoX1, y1SqrMul4, R), R - x1Pow4Mul9, R);
        }

        uint256 qElliptic = e[UltraFflonkTypes.E_Q_ELLIPTIC];
        uint256 doubleScaling = mulmod(qElliptic, e[UltraFflonkTypes.E_Q_M], R);
        // q_elliptic * (q_is_double - 1), i.e. the negation of the addition-branch selector.
        uint256 negNotDoubleScaling = addmod(doubleScaling, R - qElliptic, R);

        return addmod(mulmod(xDoubleIdentity, doubleScaling, R), R - mulmod(xAddIdentity, negNotDoubleScaling, R), R);
    }

    /// @dev Subrelation 1: the y-coordinate of P3, i.e. y3 = lambda*(x1 - x3) - y1 with the denominator
    /// cleared. The addition branch enforces (y3 + y1)(x2 - x1) + (x3 - x1)(q_sign*y2 - y1) = 0; the
    /// doubling branch enforces (y3 + y1)(2*y1) - (3*x1^2)(x1 - x3) = 0, accumulated in negated form.
    function yCoordinate(uint256[41] memory e) private pure returns (uint256) {
        uint256 x1 = e[UltraFflonkTypes.E_W_R];
        uint256 y1 = e[UltraFflonkTypes.E_W_O];
        uint256 y1PlusY3 = addmod(y1, e[UltraFflonkTypes.E_W_O_SHIFT], R);
        uint256 x2SubX1 = addmod(e[UltraFflonkTypes.E_W_L_SHIFT], R - x1, R);
        uint256 x3SubX1 = addmod(e[UltraFflonkTypes.E_W_R_SHIFT], R - x1, R);

        uint256 yAddIdentity;
        {
            // q_sign * y2 - y1, the numerator of lambda for the addition case.
            uint256 yDiff = addmod(mulmod(e[UltraFflonkTypes.E_W_4_SHIFT], e[UltraFflonkTypes.E_Q_L], R), R - y1, R);
            yAddIdentity = addmod(mulmod(y1PlusY3, x2SubX1, R), mulmod(x3SubX1, yDiff, R), R);
        }

        uint256 negYDoubleIdentity;
        {
            uint256 x1SqrMul3 = mulmod(addmod(x1, addmod(x1, x1, R), R), x1, R);
            negYDoubleIdentity = addmod(mulmod(x1SqrMul3, x3SubX1, R), mulmod(addmod(y1, y1, R), y1PlusY3, R), R);
        }

        uint256 qElliptic = e[UltraFflonkTypes.E_Q_ELLIPTIC];
        uint256 doubleScaling = mulmod(qElliptic, e[UltraFflonkTypes.E_Q_M], R);
        uint256 negNotDoubleScaling = addmod(doubleScaling, R - qElliptic, R);

        // Both branches enter negated, so sum them and negate once.
        uint256 sum =
            addmod(mulmod(yAddIdentity, negNotDoubleScaling, R), mulmod(negYDoubleIdentity, doubleScaling, R), R);
        return addmod(0, R - sum, R);
    }
}

// ----- src/relations/MemoryRelation.sol -----


/// @dev Port of relations/memory_relation.hpp — RAM/ROM memory gates: record fingerprints, sorted-trace
/// consistency for RAM and ROM, RAM timestamp jumps, and the single-value ROM LogUp argument.
library MemoryRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[8] memory out) internal pure {
        uint256 qMemory = e[UltraFflonkTypes.E_Q_MEMORY];

        // Record fingerprint residual `q_c + eta*w_l + eta_two*w_r + eta_three*w_o - w_4`. On an honest
        // RAM/ROM access gate this is zero; on a sorted RAM entry the same expression is the negated
        // access type, so it doubles as the value the boolean access check is applied to.
        uint256 memoryRecordCheck = recordCheckResidual(e, p);

        // Sorted traces are ordered by index, so the index delta between adjacent rows must be 0 or 1.
        // `negIndexDelta = w_l - w_l_shift` is 0 or -1, hence `indexDeltaIsZero` is the indicator of a
        // repeated index and `negIndexDelta^2 + negIndexDelta` vanishes exactly on {0, -1}.
        uint256 indexDeltaIsZero;
        uint256 indexIncreasesByZeroOrOne;
        {
            uint256 negIndexDelta = addmod(e[UltraFflonkTypes.E_W_L], R - e[UltraFflonkTypes.E_W_L_SHIFT], R);
            indexDeltaIsZero = addmod(negIndexDelta, 1, R);
            indexIncreasesByZeroOrOne = addmod(mulmod(negIndexDelta, negIndexDelta, R), negIndexDelta, R);
        }

        // ROM sorted-trace subrelations, selected by the ROM_CONSISTENCY_CHECK bitpattern q_1 = q_2 = 1.
        {
            uint256 romGate = mulmod(mulmod(e[UltraFflonkTypes.E_Q_L], e[UltraFflonkTypes.E_Q_R], R), qMemory, R);
            // If two adjacent ROM entries share an index, their full records (and hence both stored
            // values) must agree.
            uint256 recordDelta = addmod(e[UltraFflonkTypes.E_W_4_SHIFT], R - e[UltraFflonkTypes.E_W_4], R);
            out[1] = mulmod(mulmod(indexDeltaIsZero, recordDelta, R), romGate, R);
            out[2] = mulmod(indexIncreasesByZeroOrOne, romGate, R);
        }

        // Negated access type of the *next* sorted row, read off its own record fingerprint. The final
        // sorted RAM entry is left unselected, so checking the next row's type uniformly covers it.
        uint256 negNextGateAccessType;
        {
            uint256 acc = mulmod(e[UltraFflonkTypes.E_W_O_SHIFT], p.etaThree, R);
            acc = addmod(acc, mulmod(e[UltraFflonkTypes.E_W_R_SHIFT], p.etaTwo, R), R);
            acc = addmod(acc, mulmod(e[UltraFflonkTypes.E_W_L_SHIFT], p.eta, R), R);
            negNextGateAccessType = addmod(acc, R - e[UltraFflonkTypes.E_W_4_SHIFT], R);
        }

        // RAM sorted-trace subrelations, selected by the RAM_CONSISTENCY_CHECK bitpattern q_3 = 1.
        uint256 q3ByMemory = mulmod(e[UltraFflonkTypes.E_Q_O], qMemory, R);
        {
            // (indices match) && (next access is a read) => values match.
            uint256 valueDelta = addmod(e[UltraFflonkTypes.E_W_O_SHIFT], R - e[UltraFflonkTypes.E_W_O], R);
            uint256 gated = mulmod(indexDeltaIsZero, valueDelta, R);
            gated = mulmod(gated, addmod(negNextGateAccessType, 1, R), R);
            out[3] = mulmod(gated, q3ByMemory, R);
        }
        out[4] = mulmod(indexIncreasesByZeroOrOne, q3ByMemory, R);
        {
            // The next gate's access type is a read or a write, and nothing else.
            uint256 nextAccessTypeIsBoolean =
                addmod(mulmod(negNextGateAccessType, negNextGateAccessType, R), negNextGateAccessType, R);
            out[5] = mulmod(nextAccessTypeIsBoolean, q3ByMemory, R);
        }

        // Subrelation 0 bundles the three q_memory-gated identities that share the record fingerprint,
        // plus the (already q_3-gated) RAM access-type boolean check.
        {
            // ROM read: the record witness is consistent with (index, value1, value2). q_1 = q_2 = 1.
            uint256 identity =
                mulmod(memoryRecordCheck, mulmod(e[UltraFflonkTypes.E_Q_L], e[UltraFflonkTypes.E_Q_R], R), R);
            {
                // RAM timestamp check (q_1 = q_4 = 1): w_o holds the timestamp delta when the index
                // repeats, and zero when the index advances.
                uint256 timestampDelta = addmod(e[UltraFflonkTypes.E_W_R_SHIFT], R - e[UltraFflonkTypes.E_W_R], R);
                uint256 timestampCheck =
                    addmod(mulmod(indexDeltaIsZero, timestampDelta, R), R - e[UltraFflonkTypes.E_W_O], R);
                uint256 timestampGate = mulmod(e[UltraFflonkTypes.E_Q_4], e[UltraFflonkTypes.E_Q_L], R);
                identity = addmod(identity, mulmod(timestampCheck, timestampGate, R), R);
            }
            // RAM/ROM access gate (q_1 = q_m = 1): the record fingerprint must match w_4.
            {
                uint256 accessGate = mulmod(e[UltraFflonkTypes.E_Q_M], e[UltraFflonkTypes.E_Q_L], R);
                identity = addmod(identity, mulmod(memoryRecordCheck, accessGate, R), R);
            }
            identity = mulmod(identity, qMemory, R);

            // On sorted RAM rows the record residual is the negated access type; force it boolean.
            uint256 accessCheck = addmod(mulmod(memoryRecordCheck, memoryRecordCheck, R), memoryRecordCheck, R);
            out[0] = addmod(identity, mulmod(accessCheck, q3ByMemory, R), R);
        }

        // Single-value ROM tables use a LogUp argument rather than the sorted-trace permutation.
        out[6] = romLogupInverseCheck(e, p);
        out[7] = romLogupSum(e, p);
    }

    /// @dev `q_c + eta*w_l + eta_two*w_r + eta_three*w_o - w_4`: the record fingerprint residual.
    function recordCheckResidual(uint256[41] memory e, UltraFflonkTypes.Params memory p)
        private
        pure
        returns (uint256)
    {
        uint256 acc = mulmod(e[UltraFflonkTypes.E_W_O], p.etaThree, R);
        acc = addmod(acc, mulmod(e[UltraFflonkTypes.E_W_R], p.etaTwo, R), R);
        acc = addmod(acc, mulmod(e[UltraFflonkTypes.E_W_L], p.eta, R), R);
        acc = addmod(acc, e[UltraFflonkTypes.E_Q_C], R);
        return addmod(acc, R - e[UltraFflonkTypes.E_W_4], R);
    }

    /// @dev LogUp fingerprint denominator `rom_logup_gamma + w_l + eta*w_r + eta_two*q_c`, batching
    /// (index, value, ROM array id) with powers of eta under an independent additive challenge.
    function romLogupDenominator(uint256[41] memory e, UltraFflonkTypes.Params memory p)
        private
        pure
        returns (uint256)
    {
        uint256 acc = addmod(e[UltraFflonkTypes.E_W_L], mulmod(e[UltraFflonkTypes.E_W_R], p.eta, R), R);
        acc = addmod(acc, mulmod(e[UltraFflonkTypes.E_Q_C], p.etaTwo, R), R);
        return addmod(acc, p.romLogupGamma, R);
    }

    /// @dev Subrelation 6: on every ROM-LogUp row (table entry q_2*(1-q_1) or read access q_4*(1-q_1)),
    /// w_4 must be the inverse of the fingerprint denominator.
    function romLogupInverseCheck(uint256[41] memory e, UltraFflonkTypes.Params memory p)
        private
        pure
        returns (uint256)
    {
        uint256 oneMinusQ1 = addmod(1, R - e[UltraFflonkTypes.E_Q_L], R);
        uint256 qLogupAny = addmod(e[UltraFflonkTypes.E_Q_R], e[UltraFflonkTypes.E_Q_4], R);
        qLogupAny = mulmod(qLogupAny, oneMinusQ1, R);

        uint256 inverseIsCorrect = addmod(mulmod(e[UltraFflonkTypes.E_W_4], romLogupDenominator(e, p), R), R - 1, R);
        return mulmod(mulmod(e[UltraFflonkTypes.E_Q_MEMORY], qLogupAny, R), inverseIsCorrect, R);
    }

    /// @dev Subrelation 7 (linearly dependent, summed across the trace): read rows contribute +1/denom,
    /// table rows contribute -m_i/denom, where the multiplicity m_i lives in w_o.
    function romLogupSum(uint256[41] memory e, UltraFflonkTypes.Params memory) private pure returns (uint256) {
        uint256 oneMinusQ1 = addmod(1, R - e[UltraFflonkTypes.E_Q_L], R);
        uint256 qLogupTable = mulmod(e[UltraFflonkTypes.E_Q_R], oneMinusQ1, R);
        uint256 qLogupRead = mulmod(e[UltraFflonkTypes.E_Q_4], oneMinusQ1, R);

        uint256 contribution = addmod(qLogupRead, R - mulmod(qLogupTable, e[UltraFflonkTypes.E_W_O], R), R);
        contribution = mulmod(contribution, e[UltraFflonkTypes.E_W_4], R);
        return mulmod(contribution, e[UltraFflonkTypes.E_Q_MEMORY], R);
    }
}

// ----- src/relations/NonNativeFieldRelation.sol -----


/// @dev Port of relations/non_native_field_relation.hpp — bigfield (non-native) arithmetic over
/// 68-bit limbs: the three limb-product gates and the two 14-bit sublimb accumulation gates,
/// all gated by q_nnf.
library NonNativeFieldRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// 2^68, the bigfield limb radix (`FF LIMB_SIZE(uint256_t(1) << 68)`).
    uint256 private constant LIMB_SIZE = 0x100000000000000000;

    /// 2^14, the sublimb radix used by the limb accumulation gates
    /// (`FF SUBLIMB_SHIFT(uint256_t(1) << 14)`).
    uint256 private constant SUBLIMB_SHIFT = 0x4000;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[1] memory out) internal pure {
        p; // the non-native field relation reads no relation parameters

        // Subrelation 0: the single combined non-native field identity. The two families of gates
        // (limb products, selected by q_2; limb accumulation, selected by q_3) are summed and the
        // whole thing is switched on by q_nnf.
        uint256 identity = addmod(productIdentity(e), limbAccumulatorIdentity(e), R);
        out[0] = mulmod(identity, e[UltraFflonkTypes.E_Q_NNF], R);
    }

    /// @dev The three bigfield product gates, each selected by its own secondary selector and the
    /// family as a whole gated by q_2. They check that the cross-terms of a 4-limb x 4-limb
    /// multiplication accumulate correctly with their 2^68 weights.
    function productIdentity(uint256[41] memory e) private pure returns (uint256) {
        // The cross-term shared by all three gates: w_1 * w_2' + w_1' * w_2.
        uint256 limbSubproduct = addmod(
            mulmod(e[UltraFflonkTypes.E_W_L], e[UltraFflonkTypes.E_W_R_SHIFT], R),
            mulmod(e[UltraFflonkTypes.E_W_L_SHIFT], e[UltraFflonkTypes.E_W_R], R),
            R
        );

        // Gate 2 consumes the un-scaled subproduct, so it must be evaluated before the rescale below.
        uint256 acc = mulmod(productGate2(e, limbSubproduct), e[UltraFflonkTypes.E_Q_4], R);

        // Gates 1 and 3 share the scaled subproduct (w_1 * w_2' + w_1' * w_2) * 2^68 + w_1' * w_2'.
        limbSubproduct = mulmod(limbSubproduct, LIMB_SIZE, R);
        limbSubproduct =
            addmod(limbSubproduct, mulmod(e[UltraFflonkTypes.E_W_L_SHIFT], e[UltraFflonkTypes.E_W_R_SHIFT], R), R);

        // Gate 1 (selector q_3): scaled subproduct minus the low accumulators w_3 + w_4.
        {
            uint256 t = addmod(limbSubproduct, R - addmod(e[UltraFflonkTypes.E_W_O], e[UltraFflonkTypes.E_W_4], R), R);
            acc = addmod(acc, mulmod(t, e[UltraFflonkTypes.E_Q_O], R), R);
        }

        // Gate 3 (selector q_m): scaled subproduct + w_4 - w_3' - w_4'.
        {
            uint256 t = addmod(limbSubproduct, e[UltraFflonkTypes.E_W_4], R);
            t = addmod(t, R - addmod(e[UltraFflonkTypes.E_W_O_SHIFT], e[UltraFflonkTypes.E_W_4_SHIFT], R), R);
            acc = addmod(acc, mulmod(t, e[UltraFflonkTypes.E_Q_M], R), R);
        }

        return mulmod(acc, e[UltraFflonkTypes.E_Q_R], R);
    }

    /// @dev Bigfield product gate 2 (selector q_4), before its selector is applied:
    ///   limb_subproduct + (w_1 * w_4 + w_2 * w_3 - w_3') * 2^68 - w_4'
    function productGate2(uint256[41] memory e, uint256 limbSubproduct) private pure returns (uint256) {
        uint256 t = addmod(
            mulmod(e[UltraFflonkTypes.E_W_L], e[UltraFflonkTypes.E_W_4], R),
            mulmod(e[UltraFflonkTypes.E_W_R], e[UltraFflonkTypes.E_W_O], R),
            R
        );
        t = addmod(t, R - e[UltraFflonkTypes.E_W_O_SHIFT], R);
        t = mulmod(t, LIMB_SIZE, R);
        t = addmod(t, R - e[UltraFflonkTypes.E_W_4_SHIFT], R);
        return addmod(t, limbSubproduct, R);
    }

    /// @dev The two limb accumulation gates, gated as a family by q_3. Each reconstructs a 68-bit
    /// limb from five 14-bit sublimbs laid out across the current and next row, in Horner form.
    function limbAccumulatorIdentity(uint256[41] memory e) private pure returns (uint256) {
        uint256 acc;

        // Gate 1 (selector q_4): ((((w_2' * 2^14 + w_1') * 2^14 + w_3) * 2^14 + w_2) * 2^14 + w_1) - w_4
        {
            uint256 t = mulmod(e[UltraFflonkTypes.E_W_R_SHIFT], SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_L_SHIFT], R);
            t = mulmod(t, SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_O], R);
            t = mulmod(t, SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_R], R);
            t = mulmod(t, SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_L], R);
            t = addmod(t, R - e[UltraFflonkTypes.E_W_4], R);
            acc = mulmod(t, e[UltraFflonkTypes.E_Q_4], R);
        }

        // Gate 2 (selector q_m): ((((w_3' * 2^14 + w_2') * 2^14 + w_1') * 2^14 + w_4) * 2^14 + w_3) - w_4'
        {
            uint256 t = mulmod(e[UltraFflonkTypes.E_W_O_SHIFT], SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_R_SHIFT], R);
            t = mulmod(t, SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_L_SHIFT], R);
            t = mulmod(t, SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_4], R);
            t = mulmod(t, SUBLIMB_SHIFT, R);
            t = addmod(t, e[UltraFflonkTypes.E_W_O], R);
            t = addmod(t, R - e[UltraFflonkTypes.E_W_4_SHIFT], R);
            acc = addmod(acc, mulmod(t, e[UltraFflonkTypes.E_Q_M], R), R);
        }

        return mulmod(acc, e[UltraFflonkTypes.E_Q_O], R);
    }
}

// ----- src/relations/Poseidon2ExternalRelation.sol -----


/// @dev Port of relations/poseidon2_external_relation.hpp — one Poseidon2 external round: add the
/// round constants, apply the x^5 S-box to all four state words, multiply by the external MDS
/// matrix M_E, and constrain the result to equal the next row's witness state.
library Poseidon2ExternalRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// @dev The Poseidon2 S-box, x -> x^5.
    function sbox(uint256 x) private pure returns (uint256) {
        uint256 x2 = mulmod(x, x, R);
        uint256 x4 = mulmod(x2, x2, R);
        return mulmod(x4, x, R);
    }

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[4] memory out) internal pure {
        p; // the external round reads no relation parameters

        // S-box inputs are the current state plus this round's constants, which are carried in the
        // arithmetic selectors q_l, q_r, q_o, q_4 on Poseidon2 external rows.
        uint256[4] memory u;
        u[0] = sbox(addmod(e[UltraFflonkTypes.E_W_L], e[UltraFflonkTypes.E_Q_L], R));
        u[1] = sbox(addmod(e[UltraFflonkTypes.E_W_R], e[UltraFflonkTypes.E_Q_R], R));
        u[2] = sbox(addmod(e[UltraFflonkTypes.E_W_O], e[UltraFflonkTypes.E_Q_O], R));
        u[3] = sbox(addmod(e[UltraFflonkTypes.E_W_4], e[UltraFflonkTypes.E_Q_4], R));

        // v = M_E * u for the external matrix
        //   [5 7 1 3; 4 6 1 1; 1 3 5 7; 1 1 4 6],
        // built from shared partial sums exactly as the C++ does.
        uint256[4] memory v;
        {
            uint256 t0 = addmod(u[0], u[1], R); // u1 + u2
            uint256 t1 = addmod(u[2], u[3], R); // u3 + u4
            uint256 t2 = addmod(addmod(u[1], u[1], R), t1, R); // 2u2 + u3 + u4
            uint256 t3 = addmod(addmod(u[3], u[3], R), t0, R); // u1 + u2 + 2u4

            uint256 v2 = addmod(t0, t0, R);
            v2 = addmod(v2, v2, R);
            v2 = addmod(v2, t2, R); // 4u1 + 6u2 + u3 + u4

            uint256 v4 = addmod(t1, t1, R);
            v4 = addmod(v4, v4, R);
            v4 = addmod(v4, t3, R); // u1 + u2 + 4u3 + 6u4

            v[0] = addmod(t3, v2, R); // 5u1 + 7u2 + u3 + 3u4
            v[1] = v2;
            v[2] = addmod(t2, v4, R); // u1 + 3u2 + 5u3 + 7u4
            v[3] = v4;
        }

        // Each subrelation gates "round output equals the next row's state word" on the
        // Poseidon2 external selector.
        uint256 q = e[UltraFflonkTypes.E_Q_POSEIDON2_EXTERNAL];
        out[0] = mulmod(q, addmod(v[0], R - e[UltraFflonkTypes.E_W_L_SHIFT], R), R);
        out[1] = mulmod(q, addmod(v[1], R - e[UltraFflonkTypes.E_W_R_SHIFT], R), R);
        out[2] = mulmod(q, addmod(v[2], R - e[UltraFflonkTypes.E_W_O_SHIFT], R), R);
        out[3] = mulmod(q, addmod(v[3], R - e[UltraFflonkTypes.E_W_4_SHIFT], R), R);
    }
}

// ----- src/relations/Poseidon2InternalRelation.sol -----


/// @dev Port of relations/poseidon2_internal_relation.hpp — one Poseidon2 internal (partial) round:
/// the S-box is applied to the first state element only, the internal MDS matrix M_I is applied to
/// the resulting state, and the four outputs must equal the next row's wires.
library Poseidon2InternalRelation {
    uint256 internal constant R = UltraFflonkTypes.R;

    /// Diagonal entries of the internal matrix M_I, from
    /// crypto/poseidon2/poseidon2_params.hpp::Poseidon2Bn254ScalarFieldParams. That header stores
    /// `internal_matrix_diagonal_minus_one[i]` = D_i - 1; the values below are copied verbatim and
    /// D1 is the +1 of the first one (equal, as expected, to `internal_matrix[0][0]`).
    uint256 internal constant D1 = 0x10dc6e9c006ea38b04b1e03b4bd9490c0d03f98929ca1d7fb56821fd19d3b6e8;
    uint256 internal constant D2_MINUS_1 = 0x0c28145b6a44df3e0149b3d0a30b3bb599df9756d4dd9b84a86b38cfb45a740b;
    uint256 internal constant D3_MINUS_1 = 0x00544b8338791518b2c7645a50392798b21f75bb60e3596170067d00141cac15;
    uint256 internal constant D4_MINUS_1 = 0x222c01175718386f2e2e82eb122789e352e105a3b8fa852613bc534433ee428b;

    /// @dev Writes each subrelation's value at xi into `out`, in SUBRELATION_PARTIAL_LENGTHS order.
    function accumulate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[4] memory out) internal pure {
        // The whole relation is gated on the internal-round selector.
        uint256 qPoseidon = e[UltraFflonkTypes.E_Q_POSEIDON2_INTERNAL];

        // u_1 = (w_1 + c_0)^5, the S-box output for the only element the internal round touches.
        // The round constant c_0 for this round is carried by the q_l selector. Every subrelation
        // uses it already multiplied by the selector.
        uint256 scaledU1;
        {
            uint256 s1 = addmod(e[UltraFflonkTypes.E_W_L], e[UltraFflonkTypes.E_Q_L], R);
            uint256 s1Pow4 = mulmod(s1, s1, R);
            s1Pow4 = mulmod(s1Pow4, s1Pow4, R);
            scaledU1 = mulmod(mulmod(s1Pow4, s1, R), qPoseidon, R);
        }

        // u_2 + u_3 + u_4: the off-diagonal part of M_I is all-ones, so this sum appears in every row.
        // The untouched state elements pass through the S-box layer unchanged, so u_k = w_k for k > 1.
        uint256 partialSum;
        {
            uint256 s = addmod(e[UltraFflonkTypes.E_W_R], e[UltraFflonkTypes.E_W_O], R);
            partialSum = addmod(s, e[UltraFflonkTypes.E_W_4], R);
        }

        // Row 1: D_1*u_1 + u_2 + u_3 + u_4 == w_1_shift.
        {
            uint256 rest = addmod(partialSum, R - e[UltraFflonkTypes.E_W_L_SHIFT], R);
            out[0] = addmod(mulmod(scaledU1, D1, R), mulmod(rest, qPoseidon, R), R);
        }

        // Row 2: u_1 + D_2*u_2 + u_3 + u_4 == w_2_shift, written as (D_2 - 1)*u_2 + partialSum so the
        // shared sum can be reused.
        {
            uint256 rest = addmod(mulmod(e[UltraFflonkTypes.E_W_R], D2_MINUS_1, R), partialSum, R);
            rest = addmod(rest, R - e[UltraFflonkTypes.E_W_R_SHIFT], R);
            out[1] = addmod(mulmod(rest, qPoseidon, R), scaledU1, R);
        }

        // Row 3: u_1 + u_2 + D_3*u_3 + u_4 == w_3_shift.
        {
            uint256 rest = addmod(mulmod(e[UltraFflonkTypes.E_W_O], D3_MINUS_1, R), partialSum, R);
            rest = addmod(rest, R - e[UltraFflonkTypes.E_W_O_SHIFT], R);
            out[2] = addmod(mulmod(rest, qPoseidon, R), scaledU1, R);
        }

        // Row 4: u_1 + u_2 + u_3 + D_4*u_4 == w_4_shift.
        {
            uint256 rest = addmod(mulmod(e[UltraFflonkTypes.E_W_4], D4_MINUS_1, R), partialSum, R);
            rest = addmod(rest, R - e[UltraFflonkTypes.E_W_4_SHIFT], R);
            out[3] = addmod(mulmod(rest, qPoseidon, R), scaledU1, R);
        }

        p; // the relation reads no relation parameters
    }
}

// ----- src/UltraRelations.sol -----


/**
 * @title The Ultra relation set, evaluated at one point.
 *
 * @dev The order below is `UltraFlavor::Relations_`, which is generated from
 * `scripts/flavor-codegen/src/flavors/ultra.ts`. It decides which power of `alpha` batches which
 * subrelation, so it is protocol: reordering it here silently invalidates every proof. The mapping is
 * pinned by `RelationVectors.t.sol`, which checks all thirty-one values against barretenberg's own.
 *
 * Two of the thirty-one are "linearly dependent" — Sumcheck only requires them to sum to zero across
 * the trace, not to vanish at each row. They are still evaluated here; it is the *verifier* that
 * routes them into the running-sum identities instead of the per-row batch.
 */
library UltraRelations {
    uint256 internal constant NUM_SUBRELATIONS = 31;

    /// Global indices of the subrelations Sumcheck enforces as a trace sum, in relation order.
    uint256 internal constant SUMMED_LOOKUP = 4; // LogDerivLookup's lookup identity
    uint256 internal constant SUMMED_ROM_LOGUP = 21; // Memory's ROM-LogUp sum

    /// @dev Writes every subrelation's value at the evaluation point into `out`.
    function evaluate(uint256[41] memory e, UltraFflonkTypes.Params memory p, uint256[NUM_SUBRELATIONS] memory out)
        internal
        pure
    {
        {
            uint256[3] memory o;
            PermutationRelation.accumulate(e, p, o);
            out[0] = o[0];
            out[1] = o[1];
            out[2] = o[2];
        }
        {
            uint256[3] memory o;
            LogDerivLookupRelation.accumulate(e, p, o);
            out[3] = o[0];
            out[4] = o[1];
            out[5] = o[2];
        }
        {
            uint256[2] memory o;
            ArithmeticRelation.accumulate(e, p, o);
            out[6] = o[0];
            out[7] = o[1];
        }
        {
            uint256[4] memory o;
            DeltaRangeRelation.accumulate(e, p, o);
            out[8] = o[0];
            out[9] = o[1];
            out[10] = o[2];
            out[11] = o[3];
        }
        {
            uint256[2] memory o;
            EllipticRelation.accumulate(e, p, o);
            out[12] = o[0];
            out[13] = o[1];
        }
        {
            uint256[8] memory o;
            MemoryRelation.accumulate(e, p, o);
            for (uint256 i = 0; i < 8; ++i) {
                out[14 + i] = o[i];
            }
        }
        {
            uint256[1] memory o;
            NonNativeFieldRelation.accumulate(e, p, o);
            out[22] = o[0];
        }
        {
            uint256[4] memory o;
            Poseidon2ExternalRelation.accumulate(e, p, o);
            for (uint256 i = 0; i < 4; ++i) {
                out[23 + i] = o[i];
            }
        }
        {
            uint256[4] memory o;
            Poseidon2InternalRelation.accumulate(e, p, o);
            for (uint256 i = 0; i < 4; ++i) {
                out[27 + i] = o[i];
            }
        }
    }
}

// ----- src/UltraFflonkVerifier.sol -----


/**
 * @title fflonk over the arithmetization Noir compiles to: an L1 verifier for UltraHonk circuits.
 *
 * @notice The circuit is UltraHonk's — four wires, plookup, the custom gates, the whole ACIR
 * frontend. Only the proof system on top of it is different: a univariate quotient and a batched
 * fflonk opening rather than sumcheck and Shplemini. That trades a much heavier prover for a verifier
 * whose group work is a fixed eleven scalar multiplications and one pairing, and a proof that is a
 * fixed 2,112 bytes, whatever the circuit contains.
 *
 * @dev The mirror of `barretenberg/ultra_fflonk`; `PROTOCOL.md` there is the specification both
 * implement. The relation set below is a port of `barretenberg/relations/*.hpp`, and every one of its
 * thirty-one subrelations is checked against barretenberg's own evaluation by `RelationVectors.t.sol`
 * — the batched identity folds them into a single field element, inside which one wrong term would
 * otherwise be invisible.
 */
contract UltraFflonkVerifier {
    /// BN254 base field.
    uint256 internal constant Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
    /// BN254 scalar field. Spelled out rather than aliased: inline assembly can only reference a
    /// direct number constant, and the constructor pins it to `UltraFflonkTypes.R`.
    uint256 internal constant R = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    uint256 internal constant PROOF_LENGTH = 2112;
    uint256 internal constant NUM_EVALUATIONS = 54;
    uint256 internal constant NUM_QUOTIENT_CHUNKS = 6;
    uint256 internal constant NUM_PREPROCESSED_GROUPS = 4;
    uint256 internal constant PACK_PREPROCESSED = 7;

    /// @dev `PERMUTATION_ARGUMENT_VALUE_SEPARATOR` from `barretenberg/constants.hpp`.
    uint256 internal constant PERMUTATION_SEPARATOR = 1 << 28;

    // Byte offsets into the proof blob: four committed groups, then W and W'.
    uint256 internal constant OFF_C_WIRES = 0;
    uint256 internal constant OFF_C_MEMORY = 64;
    uint256 internal constant OFF_C_GRAND_PRODUCT = 128;
    uint256 internal constant OFF_C_QUOTIENT = 192;
    uint256 internal constant OFF_W = 256;
    uint256 internal constant OFF_WP = 320;
    uint256 internal constant OFF_EVALUATIONS = 384;

    // Offsets into the flat evaluation vector. Each group contributes its `xi` openings, then its
    // `xi*omega` ones; the order is protocol.
    uint256 internal constant FLAT_WIRES_XI = 28;
    uint256 internal constant FLAT_WIRES_XI_OMEGA = 31;
    uint256 internal constant FLAT_MEMORY_XI = 34;
    uint256 internal constant FLAT_MEMORY_XI_OMEGA = 37;
    uint256 internal constant FLAT_GRAND_PRODUCT_XI = 40;
    uint256 internal constant FLAT_GRAND_PRODUCT_XI_OMEGA = 44;
    uint256 internal constant FLAT_QUOTIENT = 48;

    // The BN254 G2 generator and the SRS's [x]_2, in the (c1, c0) ordering the precompile expects.
    uint256 internal constant G2_GEN_X_C1 = 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2;
    uint256 internal constant G2_GEN_X_C0 = 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed;
    uint256 internal constant G2_GEN_Y_C1 = 0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b;
    uint256 internal constant G2_GEN_Y_C0 = 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa;
    uint256 internal constant G2_TAU_X_C1 = 0x260e01b251f6f1c7e7ff4e580791dee8ea51d87a358e038b4efe30fac09383c1;
    uint256 internal constant G2_TAU_X_C0 = 0x0118c4d5b837bcc2bc89b5b398b5974e9f5944073b32078b7e231fec938883b0;
    uint256 internal constant G2_TAU_Y_C1 = 0x04fc6369f7110fe3d25156c1bb9a72859cf2a04641f99ba4ee413c80da6a5fe4;
    uint256 internal constant G2_TAU_Y_C0 = 0x22febda3c0c0632a56475b4214e5615e11e6dd3f96e6cea2854a87d4dacc5e55;

    // The verification key, inlined into the bytecode at deployment.
    uint256 public immutable CIRCUIT_SIZE;
    uint256 public immutable LOG_CIRCUIT_SIZE;
    uint256 public immutable NUM_PUBLIC_INPUTS;
    uint256 public immutable PUB_INPUTS_OFFSET;
    uint256 public immutable OMEGA;
    uint256 public immutable VK_HASH;
    uint256 internal immutable P0X;
    uint256 internal immutable P0Y;
    uint256 internal immutable P1X;
    uint256 internal immutable P1Y;
    uint256 internal immutable P2X;
    uint256 internal immutable P2Y;
    uint256 internal immutable P3X;
    uint256 internal immutable P3Y;

    /// @dev Challenges and the values derived from them, kept off the stack.
    struct Context {
        uint256 alpha;
        uint256 xi;
        uint256 nu;
        uint256 y;
        uint256 xiPowN;
        uint256 vanishing;
        uint256 xiOmega;
        uint256 totalVanishing;
    }

    error InvalidVerificationKey();

    /**
     * @param circuitSize the number of rows, a power of two
     * @param numPublicInputs how many public inputs the circuit exposes
     * @param pubInputsOffset the row the public inputs start at, which the permutation delta reads
     * @param omega a primitive `circuitSize`-th root of unity
     * @param preprocessed the four preprocessed group commitments, as (x, y) pairs
     */
    constructor(
        uint256 circuitSize,
        uint256 numPublicInputs,
        uint256 pubInputsOffset,
        uint256 omega,
        uint256[8] memory preprocessed
    ) {
        // The relations are written against the library's modulus and this contract's assembly against
        // its own literal; they have to be the same field.
        assert(R == UltraFflonkTypes.R);

        if (circuitSize < 8 || (circuitSize & (circuitSize - 1)) != 0) revert InvalidVerificationKey();
        if (numPublicInputs >= circuitSize) revert InvalidVerificationKey();
        if (pubInputsOffset >= circuitSize) revert InvalidVerificationKey();
        if (omega == 0 || omega >= R) revert InvalidVerificationKey();
        for (uint256 i = 0; i < NUM_PREPROCESSED_GROUPS; ++i) {
            if (!_onCurve(preprocessed[2 * i], preprocessed[2 * i + 1])) revert InvalidVerificationKey();
        }

        uint256 logN = 0;
        while ((uint256(1) << logN) != circuitSize) {
            logN++;
        }

        // omega must have order exactly circuitSize, or the domain this verifier's vanishing
        // polynomial and shift are taken over is not the one the prover committed to.
        {
            uint256 half = omega;
            for (uint256 i = 0; i + 1 < logN; ++i) {
                half = mulmod(half, half, R);
            }
            if (half == 1 || mulmod(half, half, R) != 1) revert InvalidVerificationKey();
        }

        CIRCUIT_SIZE = circuitSize;
        LOG_CIRCUIT_SIZE = logN;
        NUM_PUBLIC_INPUTS = numPublicInputs;
        PUB_INPUTS_OFFSET = pubInputsOffset;
        OMEGA = omega;
        P0X = preprocessed[0];
        P0Y = preprocessed[1];
        P1X = preprocessed[2];
        P1Y = preprocessed[3];
        P2X = preprocessed[4];
        P2Y = preprocessed[5];
        P3X = preprocessed[6];
        P3Y = preprocessed[7];
        VK_HASH = uint256(
            keccak256(
                abi.encodePacked(
                    circuitSize,
                    numPublicInputs,
                    pubInputsOffset,
                    preprocessed[0],
                    preprocessed[1],
                    preprocessed[2],
                    preprocessed[3],
                    preprocessed[4],
                    preprocessed[5],
                    preprocessed[6],
                    preprocessed[7]
                )
            )
        ) % R;
    }

    /**
     * @notice Verify a proof of this circuit for these public inputs.
     * @dev Never reverts: a malformed proof, a bad point or a failed check all return false.
     */
    function verify(bytes calldata proof, uint256[] calldata publicInputs) external view returns (bool) {
        if (proof.length != PROOF_LENGTH) return false;
        if (publicInputs.length != NUM_PUBLIC_INPUTS) return false;

        uint256[NUM_EVALUATIONS] memory ev;
        uint256[12] memory points; // C_wires, C_memory, C_grandProduct, C_quotient, W, W' as (x, y)
        if (!_parse(proof, publicInputs, ev, points)) return false;

        Context memory ctx;
        UltraFflonkTypes.Params memory params;
        if (!_challenges(proof, publicInputs, points, ctx, params)) return false;

        // Everything the protocol inverts, in one vector: the five distinct Shplonk denominators, the
        // gap between the two opening points, and the permutation delta's denominator.
        uint256[7] memory inverses;
        if (!_denominators(publicInputs, ctx, params, inverses)) return false;

        if (!_checkQuotient(ev, ctx, params)) return false;
        return _checkOpening(ev, points, inverses, ctx);
    }

    /**
     * @dev Fiat-Shamir: `state <- keccak256(state || absorbed words) mod R`, from `state = 0`, one
     * group per round of `ultra_honk/oink_prover.cpp` so the challenge schedule is Honk's.
     */
    function _challenges(
        bytes calldata proof,
        uint256[] calldata publicInputs,
        uint256[12] memory points,
        Context memory ctx,
        UltraFflonkTypes.Params memory params
    ) internal view returns (bool) {
        params.eta = _challengeWires(proof, publicInputs);
        params.etaTwo = mulmod(params.eta, params.eta, R);
        params.etaThree = mulmod(params.etaTwo, params.eta, R);
        params.romLogupGamma = uint256(keccak256(abi.encodePacked(params.eta))) % R;

        params.beta = uint256(keccak256(abi.encodePacked(params.romLogupGamma, points[2], points[3]))) % R;
        params.betaSqr = mulmod(params.beta, params.beta, R);
        params.betaCube = mulmod(params.betaSqr, params.beta, R);
        params.gamma = uint256(keccak256(abi.encodePacked(params.beta))) % R;

        ctx.alpha = uint256(keccak256(abi.encodePacked(params.gamma, points[4], points[5]))) % R;
        ctx.xi = uint256(keccak256(abi.encodePacked(ctx.alpha, points[6], points[7]))) % R;
        ctx.nu = _challengeEvaluations(proof, ctx.xi);
        ctx.y = uint256(keccak256(abi.encodePacked(ctx.nu, points[8], points[9]))) % R;

        uint256 xiPowN = ctx.xi;
        for (uint256 i = 0; i < LOG_CIRCUIT_SIZE; ++i) {
            xiPowN = mulmod(xiPowN, xiPowN, R);
        }
        // xi must miss the domain, or the vanishing polynomial is zero and every quotient claim is free.
        if (ctx.xi == 0 || xiPowN == 1) return false;

        ctx.xiPowN = xiPowN;
        ctx.vanishing = addmod(xiPowN, R - 1, R);
        ctx.xiOmega = mulmod(ctx.xi, OMEGA, R);
        return true;
    }

    /**
     * @dev The Shplonk denominators, the opening-point gap, and the permutation delta's denominator,
     * inverted together by Montgomery's trick. Writes the delta into `params` as a side effect,
     * because it is the only consumer of the last inverse.
     *
     * The four preprocessed groups have the same shape, so they share one denominator; only five
     * distinct `Z_g(y)` exist.
     */
    function _denominators(
        uint256[] calldata publicInputs,
        Context memory ctx,
        UltraFflonkTypes.Params memory params,
        uint256[7] memory inverses
    ) internal view returns (bool) {
        {
            uint256 y2 = mulmod(ctx.y, ctx.y, R);
            uint256 y3 = mulmod(y2, ctx.y, R);
            uint256 y4 = mulmod(y2, y2, R);
            uint256 y6 = mulmod(y3, y3, R);
            uint256 y7 = mulmod(y6, ctx.y, R);

            inverses[0] = addmod(y7, R - ctx.xi, R); // preprocessed: y^7 - xi
            inverses[1] = mulmod(addmod(y3, R - ctx.xi, R), addmod(y3, R - ctx.xiOmega, R), R); // wires
            inverses[2] = inverses[1]; // memory: same pack and point set
            inverses[3] = mulmod(addmod(y4, R - ctx.xi, R), addmod(y4, R - ctx.xiOmega, R), R); // grand product
            inverses[4] = addmod(y6, R - ctx.xi, R); // quotient: y^6 - xi
        }
        inverses[5] = addmod(ctx.xiOmega, R - ctx.xi, R);

        // The public inputs reach the relations only through this correction term, which is the
        // verifier's whole binding of them to the witness.
        uint256 numerator = 1;
        {
            uint256 offset = PUB_INPUTS_OFFSET;
            uint256 numeratorAcc =
                addmod(params.gamma, mulmod(params.beta, addmod(PERMUTATION_SEPARATOR, offset, R), R), R);
            uint256 denominatorAcc = addmod(params.gamma, R - mulmod(params.beta, addmod(offset, 1, R), R), R);
            uint256 denominator = 1;
            uint256 length = publicInputs.length;
            for (uint256 i = 0; i < length; ++i) {
                numerator = mulmod(numerator, addmod(numeratorAcc, publicInputs[i], R), R);
                denominator = mulmod(denominator, addmod(denominatorAcc, publicInputs[i], R), R);
                if (i + 1 < length) {
                    numeratorAcc = addmod(numeratorAcc, params.beta, R);
                    denominatorAcc = addmod(denominatorAcc, R - params.beta, R);
                }
            }
            inverses[6] = denominator;
        }

        if (!_batchInvert(inverses)) return false;
        params.publicInputDelta = mulmod(numerator, inverses[6], R);
        return true;
    }

    /**
     * @dev The batched quotient identity, entirely in the field over the claimed evaluations.
     *
     * `sum_i alpha^i R_i + sum_j alpha^{31+j} (S_j(xi omega) - S_j(xi) - f_j) = T(xi) Z_H(xi)`.
     *
     * The `alpha` power advances across *every* subrelation, including the two Sumcheck enforces as a
     * trace sum rather than per row, so a subrelation's power depends only on the flavor's relation
     * order. Those two are held back and enter through their running sums instead.
     */
    function _checkQuotient(
        uint256[NUM_EVALUATIONS] memory ev,
        Context memory ctx,
        UltraFflonkTypes.Params memory params
    ) internal pure returns (bool) {
        uint256 numerator;
        {
            uint256[31] memory sub;
            {
                uint256[41] memory ent;
                _entities(ev, ent);
                UltraRelations.evaluate(ent, params, sub);
            }

            uint256 alphaPower = 1;
            for (uint256 i = 0; i < UltraRelations.NUM_SUBRELATIONS; ++i) {
                if (i != UltraRelations.SUMMED_LOOKUP && i != UltraRelations.SUMMED_ROM_LOGUP) {
                    numerator = addmod(numerator, mulmod(alphaPower, sub[i], R), R);
                }
                alphaPower = mulmod(alphaPower, ctx.alpha, R);
            }

            // The two running sums, in relation order: the lookup identity then the ROM-LogUp sum.
            uint256[2] memory summed = [sub[UltraRelations.SUMMED_LOOKUP], sub[UltraRelations.SUMMED_ROM_LOGUP]];
            for (uint256 j = 0; j < 2; ++j) {
                uint256 shifted = ev[FLAT_GRAND_PRODUCT_XI_OMEGA + 2 + j];
                uint256 current = ev[FLAT_GRAND_PRODUCT_XI + 2 + j];
                uint256 identity = addmod(addmod(shifted, R - current, R), R - summed[j], R);
                numerator = addmod(numerator, mulmod(alphaPower, identity, R), R);
                alphaPower = mulmod(alphaPower, ctx.alpha, R);
            }
        }

        uint256 quotientAtXi;
        for (uint256 c = NUM_QUOTIENT_CHUNKS; c > 0; --c) {
            quotientAtXi = addmod(mulmod(quotientAtXi, ctx.xiPowN, R), ev[FLAT_QUOTIENT + c - 1], R);
        }
        return numerator == mulmod(quotientAtXi, ctx.vanishing, R);
    }

    /**
     * @dev Reassemble the flavor's per-row container from the proof's evaluations.
     *
     * The five shifted entities come from the `xi*omega` half of the two-point groups, which is the
     * whole reason those groups are opened twice. Three evaluations are not read here — the lookup
     * read counts, read tags and inverses at `xi*omega` — because no relation reads them shifted;
     * they are revealed only because they share a group with a column that is.
     */
    function _entities(uint256[NUM_EVALUATIONS] memory ev, uint256[41] memory ent) internal pure {
        for (uint256 i = 0; i < 28; ++i) {
            ent[i] = ev[i];
        }
        ent[UltraFflonkTypes.E_W_L] = ev[FLAT_WIRES_XI];
        ent[UltraFflonkTypes.E_W_R] = ev[FLAT_WIRES_XI + 1];
        ent[UltraFflonkTypes.E_W_O] = ev[FLAT_WIRES_XI + 2];
        ent[UltraFflonkTypes.E_W_L_SHIFT] = ev[FLAT_WIRES_XI_OMEGA];
        ent[UltraFflonkTypes.E_W_R_SHIFT] = ev[FLAT_WIRES_XI_OMEGA + 1];
        ent[UltraFflonkTypes.E_W_O_SHIFT] = ev[FLAT_WIRES_XI_OMEGA + 2];

        ent[UltraFflonkTypes.E_LOOKUP_READ_COUNTS] = ev[FLAT_MEMORY_XI];
        ent[UltraFflonkTypes.E_LOOKUP_READ_TAGS] = ev[FLAT_MEMORY_XI + 1];
        ent[UltraFflonkTypes.E_W_4] = ev[FLAT_MEMORY_XI + 2];
        ent[UltraFflonkTypes.E_W_4_SHIFT] = ev[FLAT_MEMORY_XI_OMEGA + 2];

        ent[UltraFflonkTypes.E_LOOKUP_INVERSES] = ev[FLAT_GRAND_PRODUCT_XI];
        ent[UltraFflonkTypes.E_Z_PERM] = ev[FLAT_GRAND_PRODUCT_XI + 1];
        ent[UltraFflonkTypes.E_Z_PERM_SHIFT] = ev[FLAT_GRAND_PRODUCT_XI_OMEGA + 1];
    }

    /**
     * @dev `F = sum_g s_g C_g - (sum_g s_g R_g(y)) [1] - Z_T(y) W + y W'`, then
     * `e(F, [1]_2) = e(W', [x]_2)`, with `s_g = nu^g Z_T(y)/Z_g(y)`.
     *
     * Eleven scalar multiplications and one pairing, whatever the circuit contains.
     */
    function _checkOpening(
        uint256[NUM_EVALUATIONS] memory ev,
        uint256[12] memory points,
        uint256[7] memory inverses,
        Context memory ctx
    ) internal view returns (bool) {
        // Z_T(y) = prod_g Z_g(y); the preprocessed denominator appears four times.
        {
            uint256 inverseTotal = mulmod(inverses[0], inverses[0], R);
            inverseTotal = mulmod(inverseTotal, inverseTotal, R);
            inverseTotal = mulmod(inverseTotal, mulmod(inverses[1], inverses[2], R), R);
            inverseTotal = mulmod(inverseTotal, mulmod(inverses[3], inverses[4], R), R);
            ctx.totalVanishing = _inverse(inverseTotal);
        }

        uint256[3] memory accumulator;
        uint256 constantTerm;
        {
            uint256 nuPower = 1;
            for (uint256 g = 0; g < 8; ++g) {
                uint256 denominatorIndex = g < NUM_PREPROCESSED_GROUPS ? 0 : g - NUM_PREPROCESSED_GROUPS + 1;
                uint256 scalar = mulmod(mulmod(nuPower, ctx.totalVanishing, R), inverses[denominatorIndex], R);
                constantTerm = addmod(constantTerm, mulmod(scalar, _residueAt(ev, g, inverses[5], ctx), R), R);
                if (!_accumulateGroup(accumulator, points, g, scalar)) return false;
                nuPower = mulmod(nuPower, ctx.nu, R);
            }
        }

        if (!_accumulate(accumulator, 1, 2, R - constantTerm)) return false;
        if (!_accumulate(accumulator, points[8], points[9], R - ctx.totalVanishing)) return false;
        if (!_accumulate(accumulator, points[10], points[11], ctx.y)) return false;

        // -W'. Negating zero has to stay zero, or Q would not be a canonical coordinate and the
        // precompile would reject a proof the native verifier accepts.
        uint256 negatedY = points[11] == 0 ? 0 : Q - points[11];
        return _pairing(accumulator[0], accumulator[1], points[10], negatedY);
    }

    /**
     * @dev `R_g(y)`, the residue of the group's packed polynomial modulo `Z_g`, evaluated at `y`.
     *
     * For a one-point group the residue's coefficients *are* the claimed evaluations, so this is a
     * Horner evaluation over them. For a two-point group it is the Chinese-remainder interpolant of
     * the two residues, `[B(y)(y^t - xi) - A(y)(y^t - xi omega)] / (xi omega - xi)`.
     */
    function _residueAt(uint256[NUM_EVALUATIONS] memory ev, uint256 group, uint256 inverseGap, Context memory ctx)
        internal
        pure
        returns (uint256)
    {
        if (group < NUM_PREPROCESSED_GROUPS) {
            return _horner(ev, group * PACK_PREPROCESSED, PACK_PREPROCESSED, ctx.y);
        }
        if (group == 7) {
            return _horner(ev, FLAT_QUOTIENT, NUM_QUOTIENT_CHUNKS, ctx.y);
        }

        (uint256 firstXi, uint256 firstXiOmega, uint256 pack) = group == 4
            ? (FLAT_WIRES_XI, FLAT_WIRES_XI_OMEGA, uint256(3))
            : (group == 5
                    ? (FLAT_MEMORY_XI, FLAT_MEMORY_XI_OMEGA, uint256(3))
                    : (FLAT_GRAND_PRODUCT_XI, FLAT_GRAND_PRODUCT_XI_OMEGA, uint256(4)));

        uint256 a = _horner(ev, firstXi, pack, ctx.y);
        uint256 b = _horner(ev, firstXiOmega, pack, ctx.y);
        uint256 yPowT = _power(ctx.y, pack);
        uint256 left = mulmod(b, addmod(yPowT, R - ctx.xi, R), R);
        uint256 right = mulmod(a, addmod(yPowT, R - ctx.xiOmega, R), R);
        return mulmod(addmod(left, R - right, R), inverseGap, R);
    }

    function _horner(uint256[NUM_EVALUATIONS] memory ev, uint256 first, uint256 count, uint256 y)
        internal
        pure
        returns (uint256 result)
    {
        for (uint256 i = count; i > 0; --i) {
            result = addmod(mulmod(result, y, R), ev[first + i - 1], R);
        }
    }

    function _power(uint256 base, uint256 exponent) internal pure returns (uint256 result) {
        result = 1;
        for (uint256 i = 0; i < exponent; ++i) {
            result = mulmod(result, base, R);
        }
    }

    /// @dev The preprocessed groups' commitments live in the verification key, not the proof.
    function _accumulateGroup(uint256[3] memory accumulator, uint256[12] memory points, uint256 group, uint256 scalar)
        internal
        view
        returns (bool)
    {
        if (group == 0) return _accumulate(accumulator, P0X, P0Y, scalar);
        if (group == 1) return _accumulate(accumulator, P1X, P1Y, scalar);
        if (group == 2) return _accumulate(accumulator, P2X, P2Y, scalar);
        if (group == 3) return _accumulate(accumulator, P3X, P3Y, scalar);
        uint256 base = 2 * (group - NUM_PREPROCESSED_GROUPS);
        return _accumulate(accumulator, points[base], points[base + 1], scalar);
    }

    /**
     * @dev Read the proof, rejecting non-canonical scalars and points that are not on the curve.
     *
     * Read with `calldataload` rather than by slicing: at sixty-six words the per-slice bounds
     * checking would be the largest non-cryptographic cost in the verifier. The length was already
     * checked by the caller, which is what makes the unchecked reads safe.
     */
    function _parse(
        bytes calldata proof,
        uint256[] calldata publicInputs,
        uint256[NUM_EVALUATIONS] memory ev,
        uint256[12] memory points
    ) internal pure returns (bool) {
        for (uint256 i = 0; i < publicInputs.length; ++i) {
            if (publicInputs[i] >= R) return false;
        }

        uint256 canonical;
        assembly {
            let cursor := proof.offset
            for { let i := 0 } lt(i, 12) { i := add(i, 1) } {
                mstore(add(points, mul(i, 0x20)), calldataload(add(cursor, mul(i, 0x20))))
            }
            cursor := add(cursor, OFF_EVALUATIONS)
            canonical := 1
            for { let i := 0 } lt(i, NUM_EVALUATIONS) { i := add(i, 1) } {
                let value := calldataload(add(cursor, mul(i, 0x20)))
                // A scalar at or above the modulus must be rejected rather than reduced, or a proof
                // would have many encodings and the transcript would not bind it.
                if iszero(lt(value, R)) { canonical := 0 }
                mstore(add(ev, mul(i, 0x20)), value)
            }
        }
        if (canonical != 1) return false;

        for (uint256 i = 0; i < 6; ++i) {
            // The point at infinity is not accepted. An honest prover never produces one - it would
            // mean a committed polynomial was identically zero - and rejecting keeps this verifier and
            // the native one identical on every input.
            if (!_onCurve(points[2 * i], points[2 * i + 1])) return false;
        }
        return true;
    }

    /// @dev keccak256(0 || vkHash || publicInputs || C_wires), the first challenge.
    function _challengeWires(bytes calldata proof, uint256[] calldata publicInputs)
        internal
        view
        returns (uint256 eta)
    {
        uint256 vkHash = VK_HASH;
        assembly {
            let length := mul(publicInputs.length, 0x20)
            let ptr := mload(0x40)
            mstore(ptr, 0)
            mstore(add(ptr, 0x20), vkHash)
            calldatacopy(add(ptr, 0x40), publicInputs.offset, length)
            calldatacopy(add(add(ptr, 0x40), length), add(proof.offset, OFF_C_WIRES), 0x40)
            mstore(0x40, add(add(ptr, 0x80), length))
            eta := mod(keccak256(ptr, add(0x80, length)), R)
        }
    }

    /// @dev keccak256(xi || the fifty-four evaluations), copied straight out of calldata.
    function _challengeEvaluations(bytes calldata proof, uint256 xi) internal pure returns (uint256 nu) {
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, xi)
            calldatacopy(add(ptr, 0x20), add(proof.offset, OFF_EVALUATIONS), mul(NUM_EVALUATIONS, 0x20))
            mstore(0x40, add(ptr, add(0x20, mul(NUM_EVALUATIONS, 0x20))))
            nu := mod(keccak256(ptr, add(0x20, mul(NUM_EVALUATIONS, 0x20))), R)
        }
    }

    /**
     * @dev `accumulator += (px, py) * scalar`, laid out so that ecMul writes its result exactly where
     * ecAdd expects its second operand. Two staticcalls, no copying.
     */
    function _accumulate(uint256[3] memory accumulator, uint256 px, uint256 py, uint256 scalar)
        internal
        view
        returns (bool ok)
    {
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, mload(accumulator))
            mstore(add(ptr, 0x20), mload(add(accumulator, 0x20)))
            mstore(add(ptr, 0x40), px)
            mstore(add(ptr, 0x60), py)
            mstore(add(ptr, 0x80), scalar)

            ok := staticcall(gas(), 0x07, add(ptr, 0x40), 0x60, add(ptr, 0x40), 0x40)
            ok := and(ok, staticcall(gas(), 0x06, ptr, 0x80, ptr, 0x40))

            mstore(accumulator, mload(ptr))
            mstore(add(accumulator, 0x20), mload(add(ptr, 0x20)))
        }
    }

    /// @dev e(a, [1]_2) * e(b, [x]_2) == 1: two pairs, 384 bytes, written straight into scratch.
    function _pairing(uint256 ax, uint256 ay, uint256 bx, uint256 by) internal view returns (bool ok) {
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, ax)
            mstore(add(ptr, 0x20), ay)
            mstore(add(ptr, 0x40), G2_GEN_X_C1)
            mstore(add(ptr, 0x60), G2_GEN_X_C0)
            mstore(add(ptr, 0x80), G2_GEN_Y_C1)
            mstore(add(ptr, 0xa0), G2_GEN_Y_C0)
            mstore(add(ptr, 0xc0), bx)
            mstore(add(ptr, 0xe0), by)
            mstore(add(ptr, 0x100), G2_TAU_X_C1)
            mstore(add(ptr, 0x120), G2_TAU_X_C0)
            mstore(add(ptr, 0x140), G2_TAU_Y_C1)
            mstore(add(ptr, 0x160), G2_TAU_Y_C0)
            mstore(0x40, add(ptr, 0x180))
            ok := staticcall(gas(), 0x08, ptr, 0x180, ptr, 0x20)
            ok := and(ok, eq(mload(ptr), 1))
        }
    }

    /// @dev Montgomery's trick: one modular exponentiation for the whole vector.
    function _batchInvert(uint256[7] memory values) internal view returns (bool) {
        uint256[7] memory prefix;
        uint256 running = 1;
        for (uint256 i = 0; i < 7; ++i) {
            if (values[i] == 0) return false;
            running = mulmod(running, values[i], R);
            prefix[i] = running;
        }

        uint256 inverse = _inverse(running);
        for (uint256 i = 7; i > 1; --i) {
            uint256 value = values[i - 1];
            values[i - 1] = mulmod(inverse, prefix[i - 2], R);
            inverse = mulmod(inverse, value, R);
        }
        values[0] = inverse;
        return true;
    }

    /// @dev `value^(R-2) mod R` via the modexp precompile.
    function _inverse(uint256 value) internal view returns (uint256 result) {
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, 0x20)
            mstore(add(ptr, 0x20), 0x20)
            mstore(add(ptr, 0x40), 0x20)
            mstore(add(ptr, 0x60), value)
            mstore(add(ptr, 0x80), sub(R, 2))
            mstore(add(ptr, 0xa0), R)
            if iszero(staticcall(gas(), 0x05, ptr, 0xc0, ptr, 0x20)) { revert(0, 0) }
            result := mload(ptr)
        }
    }

    /// @dev `y^2 == x^3 + 3` over the base field, with canonical coordinates. Rejects infinity.
    function _onCurve(uint256 x, uint256 y) internal pure returns (bool) {
        if (x >= Q || y >= Q) return false;
        if (x == 0 && y == 0) return false;
        return mulmod(y, y, Q) == addmod(mulmod(mulmod(x, x, Q), x, Q), 3, Q);
    }
}
)CONTRACT";

} // namespace bb
