#!/usr/bin/env bash
# Regenerate dsl/acir_proofs/ultra_fflonk_contract.hpp from the verifier sources.
#
# The .sol files are the source of truth - they are what the Foundry suite in this directory tests,
# and what the fixture exporter's proofs are checked against. The header flattens them into one
# self-contained contract so that `bb write_solidity_verifier --scheme ultra_fflonk` can emit
# something deployable without reading anything off disk at runtime.
#
# Flattening means stripping each file's own SPDX line, pragma and imports and concatenating in
# dependency order; Solidity has no module system, so this is what "self-contained" costs.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output="${here}/../../dsl/acir_proofs/ultra_fflonk_contract.hpp"

ordered=(
  "src/UltraFflonkTypes.sol"
  "src/relations/PermutationRelation.sol"
  "src/relations/LogDerivLookupRelation.sol"
  "src/relations/ArithmeticRelation.sol"
  "src/relations/DeltaRangeRelation.sol"
  "src/relations/EllipticRelation.sol"
  "src/relations/MemoryRelation.sol"
  "src/relations/NonNativeFieldRelation.sol"
  "src/relations/Poseidon2ExternalRelation.sol"
  "src/relations/Poseidon2InternalRelation.sol"
  "src/UltraRelations.sol"
  "src/UltraFflonkVerifier.sol"
)

for file in "${ordered[@]}"; do
  if grep -q 'CONTRACT' "${here}/${file}"; then
    echo "error: ${file} contains the raw-string delimiter CONTRACT" >&2
    exit 1
  fi
done

{
  echo '// AUTOGENERATED FILE - do not edit. Regenerate with:'
  echo '//   barretenberg/cpp/src/barretenberg/ultra_fflonk/solidity/generate_contract_header.sh'
  echo '//'
  echo '// The verifier source of truth is barretenberg/cpp/src/barretenberg/ultra_fflonk/solidity/src/,'
  echo '// which is what the Foundry suite there tests. This header is those files flattened into one'
  echo '// translation unit, so that `bb write_solidity_verifier --scheme ultra_fflonk` can emit a'
  echo '// self-contained contract.'
  echo '#pragma once'
  echo
  echo '#include <string_view>'
  echo
  echo 'namespace bb {'
  echo
  echo 'static constexpr std::string_view ULTRA_FFLONK_VERIFIER_SOURCE = R"CONTRACT('
  echo '// SPDX-License-Identifier: Apache-2.0'
  echo 'pragma solidity >=0.8.21;'
  for file in "${ordered[@]}"; do
    echo
    echo "// ----- ${file} -----"
    grep -v -E '^\s*(// SPDX-License-Identifier|pragma solidity|import ")' "${here}/${file}"
  done
  echo ')CONTRACT";'
  echo
  echo '} // namespace bb'
} > "${output}"

echo "wrote ${output}"
