#!/usr/bin/env bash
# Regenerate dsl/acir_proofs/fflonk_contract.hpp from the verifier source.
#
# The .sol file is the source of truth - it is what the Foundry suite in this directory tests, and
# what the fixture exporter's proofs are checked against. The header is a verbatim copy so that
# `bb write_solidity_verifier --scheme fflonk` can emit a self-contained contract without reading
# anything off disk at runtime.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source_file="${here}/src/FflonkVerifier.sol"
output="${here}/../../dsl/acir_proofs/fflonk_contract.hpp"

if grep -q 'CONTRACT' "${source_file}"; then
  echo "error: ${source_file} contains the raw-string delimiter CONTRACT" >&2
  exit 1
fi

{
  echo '// AUTOGENERATED FILE - do not edit. Regenerate with:'
  echo '//   barretenberg/cpp/src/barretenberg/fflonk/solidity/generate_contract_header.sh'
  echo '//'
  echo '// The verifier source of truth is barretenberg/cpp/src/barretenberg/fflonk/solidity/src/FflonkVerifier.sol,'
  echo '// which is what the Foundry suite there tests. This header is that file verbatim, so that'
  echo '// `bb write_solidity_verifier --scheme fflonk` can emit a self-contained contract.'
  echo '#pragma once'
  echo
  echo '#include <string_view>'
  echo
  echo 'namespace bb {'
  echo
  echo 'static constexpr std::string_view FFLONK_VERIFIER_SOURCE = R"CONTRACT('
  cat "${source_file}"
  echo ')CONTRACT";'
  echo
  echo '} // namespace bb'
} > "${output}"

echo "wrote ${output}"
