#include "barretenberg/common/log.hpp"
#include "barretenberg/common/throw_or_abort.hpp"
#include "barretenberg/fflonk/prover.hpp"
#include "barretenberg/fflonk/verifier.hpp"
#include "barretenberg/srs/global_crs.hpp"

#include <chrono>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

// Proves a circuit of a requested size and writes the Solidity gas harness's fixture: the
// verification key as constants, the proof as a hex literal, and the public inputs. The proof is
// verified natively first, so a fixture that reaches Foundry is one the native verifier accepts -
// which is what makes the harness a cross-check of two implementations rather than a test of one.
//
// Usage: fflonk_solidity_export_bench [--log-n <k>] [--public-inputs <l>] [-o <path>]

namespace {

using namespace bb;
using namespace bb::fflonk_plonk;

/**
 * @brief A circuit of roughly `2^log_n` rows that exercises every part of the arithmetization.
 * @details Multiplication and addition gates chained so almost every wire slot is in a copy-
 * constraint cycle of length two or more, which is what makes the permutation argument do work.
 */
CircuitBuilder build_circuit(size_t log_n, size_t num_public_inputs)
{
    CircuitBuilder builder;

    std::vector<uint32_t> publics;
    for (size_t i = 0; i < num_public_inputs; ++i) {
        publics.push_back(builder.add_public_input(FF(static_cast<uint64_t>(i) + 3)));
    }

    const size_t target = (size_t(1) << log_n) - num_public_inputs - 16;
    uint32_t accumulator = publics.empty() ? builder.add_variable(FF(7)) : publics[0];
    while (builder.num_rows() + 2 < target) {
        const uint32_t operand = builder.add_variable(FF(static_cast<uint64_t>(builder.num_gates()) + 1));
        accumulator = builder.create_mul(accumulator, operand);
        accumulator = builder.create_add(accumulator, operand);
    }
    builder.fix_variable(accumulator, builder.get_variable(accumulator));

    return builder;
}

std::string to_hex(const uint256_t& value)
{
    std::ostringstream stream;
    stream << "0x" << std::hex << std::setfill('0');
    for (size_t limb = 4; limb-- > 0;) {
        stream << std::setw(16) << value.data[limb];
    }
    return stream.str();
}

std::string to_hex(std::span<const uint8_t> bytes)
{
    std::ostringstream stream;
    stream << std::hex << std::setfill('0');
    for (const uint8_t byte : bytes) {
        stream << std::setw(2) << static_cast<unsigned>(byte);
    }
    return stream.str();
}

double milliseconds_since(const std::chrono::steady_clock::time_point& start)
{
    const auto elapsed = std::chrono::steady_clock::now() - start;
    return std::chrono::duration<double, std::milli>(elapsed).count();
}

/** @brief One exported proof: the circuit shape, the key, the proof, and what it cost to make. */
struct Case {
    size_t log_n;
    size_t num_public_inputs;
    VerificationKey vk;
    std::vector<uint8_t> proof;
    std::vector<FF> public_inputs;
    double preprocess_ms;
    double prove_ms;
    double verify_ms;
};

Case run_case(size_t log_n, size_t num_public_inputs)
{
    const CircuitBuilder builder = build_circuit(log_n, num_public_inputs);

    auto start = std::chrono::steady_clock::now();
    const ProvingKey key = preprocess(builder, size_t(1) << log_n);
    const double preprocess_ms = milliseconds_since(start);

    std::string failure;
    if (!key.trace.check(failure)) {
        throw_or_abort("fflonk-solidity-export: the circuit is not satisfied: " + failure);
    }

    start = std::chrono::steady_clock::now();
    const Proof proof = prove(key);
    const double prove_ms = milliseconds_since(start);

    std::vector<uint8_t> proof_bytes = proof.to_buffer();

    start = std::chrono::steady_clock::now();
    const bool verified = verify(key.verification_key, proof_bytes, key.trace.public_inputs);
    const double verify_ms = milliseconds_since(start);

    if (!verified) {
        throw_or_abort("fflonk-solidity-export: the native verifier rejected its own proof");
    }

    return Case{ .log_n = log_n,
                 .num_public_inputs = num_public_inputs,
                 .vk = key.verification_key,
                 .proof = std::move(proof_bytes),
                 .public_inputs = key.trace.public_inputs,
                 .preprocess_ms = preprocess_ms,
                 .prove_ms = prove_ms,
                 .verify_ms = verify_ms };
}

std::string render_fixture(const std::vector<Case>& cases)
{
    std::ostringstream out;
    out << "// SPDX-License-Identifier: Apache-2.0\n"
        << "pragma solidity >=0.8.21;\n\n"
        << "// GENERATED by fflonk_solidity_export_bench - do not edit.\n"
        << "// Every proof here was accepted by barretenberg's own verifier before being written out,\n"
        << "// so the Solidity harness that consumes it is a cross-check of two implementations.\n"
        << "library Fixture {\n"
        << "    uint256 internal constant COUNT = " << cases.size() << ";\n\n"
        << "    struct Case {\n"
        << "        uint256 circuitSize;\n"
        << "        uint256 numPublicInputs;\n"
        << "        uint256 omega;\n"
        << "        uint256 k1;\n"
        << "        uint256 k2;\n"
        << "        uint256 c0x;\n"
        << "        uint256 c0y;\n"
        << "        bytes proof;\n"
        << "        uint256[] publicInputs;\n"
        << "    }\n\n"
        << "    function get(uint256 index) internal pure returns (Case memory) {\n";
    for (size_t i = 0; i < cases.size(); ++i) {
        out << "        if (index == " << i << ") return _case" << i << "();\n";
    }
    out << "        revert(\"fixture: no such case\");\n"
        << "    }\n";

    for (size_t i = 0; i < cases.size(); ++i) {
        const Case& c = cases[i];
        out << "\n    /// 2^" << c.log_n << " rows, " << c.num_public_inputs << " public inputs.\n"
            << "    function _case" << i << "() private pure returns (Case memory c) {\n"
            << "        c.circuitSize = " << c.vk.circuit_size << ";\n"
            << "        c.numPublicInputs = " << c.vk.num_public_inputs << ";\n"
            << "        c.omega = " << to_hex(static_cast<uint256_t>(c.vk.omega)) << ";\n"
            << "        c.k1 = " << to_hex(static_cast<uint256_t>(c.vk.k1)) << ";\n"
            << "        c.k2 = " << to_hex(static_cast<uint256_t>(c.vk.k2)) << ";\n"
            << "        c.c0x = " << to_hex(static_cast<uint256_t>(c.vk.c0.x)) << ";\n"
            << "        c.c0y = " << to_hex(static_cast<uint256_t>(c.vk.c0.y)) << ";\n"
            << "        c.proof = hex\"" << to_hex(c.proof) << "\";\n"
            << "        c.publicInputs = new uint256[](" << c.public_inputs.size() << ");\n";
        for (size_t j = 0; j < c.public_inputs.size(); ++j) {
            out << "        c.publicInputs[" << j << "] = " << to_hex(static_cast<uint256_t>(c.public_inputs[j]))
                << ";\n";
        }
        out << "    }\n";
    }
    out << "}\n";
    return out.str();
}

} // namespace

int main(int argc, char** argv)
{
    std::string output_path = "src/barretenberg/fflonk/solidity/test/Fixture.sol";
    std::vector<std::pair<size_t, size_t>> shapes = { { 8, 1 }, { 12, 4 }, { 16, 16 }, { 19, 4 } };

    for (int i = 1; i + 1 < argc; i += 2) {
        const std::string flag = argv[i];
        if (flag == "-o") {
            output_path = argv[i + 1];
        } else if (flag == "--shapes") {
            // "log_n:public_inputs,log_n:public_inputs,..."
            shapes.clear();
            std::istringstream stream(argv[i + 1]);
            std::string item;
            while (std::getline(stream, item, ',')) {
                const size_t colon = item.find(':');
                shapes.emplace_back(std::stoul(item.substr(0, colon)), std::stoul(item.substr(colon + 1)));
            }
        }
    }

    srs::init_file_crs_factory(srs::bb_crs_path());

    std::vector<Case> cases;
    for (const auto& [log_n, num_public_inputs] : shapes) {
        cases.push_back(run_case(log_n, num_public_inputs));
        const Case& c = cases.back();
        std::cerr << "fflonk-solidity-export: 2^" << c.log_n << " rows, " << c.num_public_inputs
                  << " public inputs, proof " << c.proof.size() << " bytes | preprocess " << std::fixed
                  << std::setprecision(1) << c.preprocess_ms << " ms, prove " << c.prove_ms << " ms, verify "
                  << std::setprecision(2) << c.verify_ms << " ms\n";
    }

    std::ofstream stream(output_path);
    if (!stream) {
        std::cerr << "fflonk-solidity-export: cannot write " << output_path << "\n";
        return 1;
    }
    stream << render_fixture(cases);
    std::cerr << "fflonk-solidity-export: wrote " << output_path << "\n";
    return 0;
}
